// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcidStep = { enabled: boolean, pitchOffset: number, accent: boolean, slide: boolean, };
