// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcidStep } from "./AcidStep";

export type AcidLineParams = { cutoffHz: number, resonance: number, envelopeAmount: number, decayMs: number, accentAmount: number, slideMs: number, pulseMix: number, gain: number, sequencer: boolean, gate: number, manualSlide: boolean, steps: [AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep, AcidStep], };
