// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls for [`super::AcousticString`], a dispersive dual-string model.
 */
export type AcousticStringParams = { 
/**
 * Nominal decay, 0.2–24 seconds; default 6.
 */
decaySeconds: number, 
/**
 * Loop brightness, 0–1; default 0.75.
 */
brightness: number, 
/**
 * First-order allpass dispersion, 0–1; default 0.3.
 */
stiffness: number, 
/**
 * Contribution of the second, three-cent-detuned string, 0–1; default 0.45.
 */
sympathetic: number, 
/**
 * Excitation position, 0.05–0.95; default 0.27.
 */
pickPosition: number, 
/**
 * Output gain, 0–1; default 0.8.
 */
level: number, };
