// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisStatus } from "./AnalysisStatus";

export type AnalysisJob = { job: string, ticket: string, request: string, sequence: string, status: AnalysisStatus, completedWork: string, maximumWork: string, failure: string | null, };
