// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisProvenance = { origin: string, sourceRevision: string, author: string, licenseSpdx: string, licenseReference: string, adapterId: string, adapterVersion: string, device: string, };
