// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisApply = { ticket: string, 
/**
 * The submit request shown by the review. A mismatched/stale UI is refused.
 */
request: string, 
/**
 * Replacement requires the complete rendered clip selection. Otherwise
 * derived clips are added without deleting any original source or clip.
 */
replaceOriginal: boolean, };
