// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnalysisArtifact = { name: string, role: string, frames: string, channels: number, sampleRate: number, frameOrigin: string, bytes: string, sha256: string, };
