// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Waveform } from "./Waveform";

export type AnalogOscParams = { waveform: Waveform, semitones: number, detuneCents: number, level: number, };
