// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisArtifact } from "./AnalysisArtifact";
import type { AnalysisJob } from "./AnalysisJob";
import type { AnalysisModel } from "./AnalysisModel";
import type { ClipId } from "./ClipId";

export type AnalysisReview = { job: AnalysisJob, clip: ClipId, generation: string, editRevision: string, sourceSha256: string, bindingSha256: string, startFrame: string, endFrame: string, inputFrames: string, model: AnalysisModel, artifacts: Array<AnalysisArtifact>, };
