// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisOutputRole } from "./AnalysisOutputRole";
import type { AnalysisProvenance } from "./AnalysisProvenance";

export type AnalysisModel = { id: string, version: string, revision: string, sha256: string, bytes: string, maxBytes: string, provenance: AnalysisProvenance, sampleRate: number, inputChannels: number, maxInputFrames: string, outputs: Array<AnalysisOutputRole>, };
