// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisModel } from "./AnalysisModel";

export type AnalysisCapability = { native: boolean, available: boolean, reason: string | null, models: Array<AnalysisModel>, };
