// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArpeggiatorMode } from "./ArpeggiatorMode";
import type { ChannelNoteDivision } from "./ChannelNoteDivision";

export type ArpeggiatorSettings = { mode: ArpeggiatorMode, rate: ChannelNoteDivision, gate: number, rangeOctaves: number, };
