// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipId } from "./ClipId";
import type { PlaylistTrackId } from "./PlaylistTrackId";

export type Arrangement = { id: number, name: string, clips: Array<ClipId>, tracks: Array<PlaylistTrackId>, };
