// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arrangement } from "./Arrangement";
import type { ClipGroup } from "./ClipGroup";
import type { PlaylistTrackId } from "./PlaylistTrackId";
import type { TrackGroup } from "./TrackGroup";
import type { TrackKind } from "./TrackKind";

export type ArrangementBook = { arrangements: Array<Arrangement>, 
/**
 * None only for the legacy/default empty book.
 */
active: number | null, trackGroups: Array<TrackGroup>, 
/**
 * Child group -> parent group. Roots have no entry.
 */
groupParents: { [key in number]: number }, 
/**
 * Playlist track -> owning group. Ungrouped tracks have no entry.
 */
trackParents: { [key in PlaylistTrackId]: number }, clipGroups: Array<ClipGroup>, linkedTracks: { [key in PlaylistTrackId]: TrackKind }, };
