// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioEditOperation } from "./AudioEditOperation";

export type AudioEditRequest = { token: number, operation: AudioEditOperation, 
/**
 * Inclusive first frame and exclusive end frame of the clip view.
 */
startFrame: number, endFrame: number, };
