// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioDevice = { name: string, isDefault: boolean, 
/**
 * Sample rates the device accepts, ascending.
 */
sampleRates: Array<number>, 
/**
 * Smallest and largest buffer size in frames, when the driver says.
 */
minBufferFrames: number | null, maxBufferFrames: number | null, 
/**
 * Channel counts the driver offers across its writable configurations.
 */
outputChannels?: Array<number>, };
