// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioEditOperation = "trim" | "extract" | "normalize" | "reverse" | "fadeIn" | "fadeOut" | "silence" | "cut";
