// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioClipPatch } from "./AudioClipPatch";
import type { ClipId } from "./ClipId";

export type AudioClipUpdate = { id: ClipId, patch: AudioClipPatch, };
