// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The audio output the user asked for. `None` means the system default.
 */
export type AudioSettings = { host?: string, device?: string, sampleRate?: number, bufferFrames?: number, };
