// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipId } from "./ClipId";

export type AudioEditPreview = { token: number, clip: ClipId, name: string, frames: number, sampleRate: number, 
/**
 * Stereo min/max envelope, retaining opposite-phase channels.
 */
peaks: Array<number>, };
