// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipId } from "./ClipId";

export type AudioCompSegment = { clip: ClipId, 
/**
 * Absolute song ticks chosen from the source clip's visible range.
 */
start: number, end: number, };
