// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackId } from "./TrackId";

/**
 * The fields of [`ClipContent::Audio`], which says what each one means.
 * The sample of a clip cannot be changed: a clip of another sample is
 * another clip.
 */
export type AudioClipPatch = { mixerTrack?: TrackId, gain?: number, pan?: number, fadeIn?: number, fadeOut?: number, reverse?: boolean, pitch?: number, };
