// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTakeLane } from "./AudioTakeLane";
import type { ClipId } from "./ClipId";

export type AudioTakeGroup = { 
/**
 * A global project ID, allocated by the native command.
 */
id: number, name: string, lanes: Array<AudioTakeLane>, comp?: Array<ClipId>, };
