// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved hardware route. Device availability is resolved when opening input.
 */
export type AudioInputRoute = { host: string, device: string, left: number, right: number | null, };
