// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point of an automation curve.
 */
export type AutomationPoint = { 
/**
 * Ticks from the start of the curve, at most [`MAX_SONG_TICKS`].
 */
tick: number, 
/**
 * 0 to 1 across the target's range. What that is in the target's own
 * unit depends on the target: see [`AutomationTarget`] and
 * [`AutomationRange`](crate::automation::AutomationRange).
 */
value: number, 
/**
 * How the curve bends on its way from this point to the next, from
 * -1 to 1, with 0 a straight line. A positive value holds back and
 * catches up at the end, a negative one moves fast first and settles:
 * [`curve_shape`](crate::automation::curve_shape) has the formula.
 */
curve: number, 
/**
 * Makes the curve a step: it stays on this point's value until the
 * next point and jumps there.
 */
hold: boolean, };
