// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationId } from "./AutomationId";
import type { AutomationPoint } from "./AutomationPoint";
import type { AutomationTarget } from "./AutomationTarget";

/**
 * A curve that moves one thing in the project while the song plays: a
 * filter sweep, a volume ride, a send that opens for one word.
 *
 * An automation does nothing by itself. Clips on the playlist
 * ([`ClipContent::Automation`]) say where in the song it plays, and
 * [`ClipContent::Automation`] says what the target does there and
 * elsewhere. Several automations may have the same target.
 *
 * An automation lives as long as its target does: deleting the channel,
 * mixer track, send or effect it moves deletes the automation and its
 * clips with it, and undo brings all of it back.
 */
export type Automation = { id: AutomationId, name: string, 
/**
 * Display color as 0xRRGGBB.
 */
color: number, target: AutomationTarget, 
/**
 * The curve: at least one point and at most
 * [`MAX_AUTOMATION_POINTS`], in order of their ticks. Two points may
 * share a tick, which makes the curve jump there.
 * [`curve_value`](crate::automation::curve_value) reads it.
 */
points: Array<AutomationPoint>, };
