// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationId } from "./AutomationId";

/**
 * What one automation is doing to its target at this moment.
 */
export type AutomatedValue = { automation: AutomationId, 
/**
 * 0 to 1 across the target's range, like the value of a point of the
 * automation's curve.
 */
value: number, };
