// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { EffectId } from "./EffectId";
import type { TrackId } from "./TrackId";

/**
 * What an automation moves. Each kind says what a point's value of 0 to 1
 * means for it; [`Project::automation_range`] gives the same as numbers.
 */
export type AutomationTarget = { type: "sidechainGain", track: TrackId, target: TrackId } | { type: "trackParam", track: TrackId, param: number } | { "type": "channelVolume", channel: ChannelId, } | { "type": "channelPan", channel: ChannelId, } | { "type": "trackVolume", track: TrackId, } | { "type": "trackPan", track: TrackId, } | { "type": "sendGain", track: TrackId, target: TrackId, } | { "type": "effectParam", track: TrackId, effect: EffectId, param: number, } | { "type": "effectMix", track: TrackId, effect: EffectId, } | { "type": "instrumentParam", channel: ChannelId, param: number, } | { "type": "tempo" };
