// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationTaper } from "./AutomationTaper";

/**
 * The range of what an automation moves, in the target's own unit, and
 * how the automation's values 0 to 1 map onto it.
 */
export type AutomationRange = { 
/**
 * The value at 0.
 */
min: number, 
/**
 * The value at 1.
 */
max: number, taper: AutomationTaper, };
