// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an automation: a curve and what it moves.
 */
export type AutomationId = number;
