// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the values 0 to 1 of an automation spread over a target's range.
 */
export type AutomationTaper = "linear" | "logarithmic" | "square" | "stepped" | "toggle";
