// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BalanceParams = { 
/**
 * Linear gain, 0 to 4; default 1. Zero is silence.
 */
gain: number, 
/**
 * Stereo balance, -1 (left only) to 1 (right only); default 0.
 * The opposite channel is attenuated; the favored channel is unchanged.
 */
pan: number, };
