// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BandDelayParams = { lowHz: number, highHz: number, timeMs: [number, number, number], level: [number, number, number], pan: [number, number, number], feedback: [number, number, number], mix: number, };
