// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandCount } from "./BandCount";

export type BandSplitParams = { bands: BandCount, 
/**
 * Hz; the sole split point in two-band mode.
 */
lowCrossoverHz: number, 
/**
 * Hz; internally constrained above the lower edge and below Nyquist.
 */
highCrossoverHz: number, lowGainDb: number, 
/**
 * Ignored in two-band mode; upper bands both use high_gain_db.
 */
midGainDb: number, highGainDb: number, };
