// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Independent stereo-linked peak dynamics settings for one band.
 */
export type BandDynamicsParams = { thresholdDb: number, ratio: number, attackMs: number, releaseMs: number, makeupDb: number, };
