// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BassShelfParams = { 
/**
 * Shelf midpoint in Hz, 40..=1000; default 150. Limited to 0.49 * rate.
 */
frequencyHz: number, 
/**
 * Low-frequency boost in dB, 0..=18; default 0 (exact unity).
 * Reserve this much steady-state headroom upstream; no limiter is added.
 */
gainDb: number, };
