// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How samples are stored in a WAV or FLAC file. The other formats have no
 * bit depth and ignore it.
 */
export type BitDepth = "int16" | "int24" | "float32";
