// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserRootKind } from "./BrowserRootKind";

/**
 * A top-level folder in the browser panel.
 */
export type BrowserRoot = { name: string, path: string, kind: BrowserRootKind, };
