// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserEntryKind } from "./BrowserEntryKind";

export type BrowserEntry = { name: string, 
/**
 * Absolute path.
 */
path: string, kind: BrowserEntryKind, };
