// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelLfoSettings } from "./ChannelLfoSettings";
import type { ModulationEnvelope } from "./ModulationEnvelope";

export type ChannelEnvelopes = { filter: ModulationEnvelope, pitch: ModulationEnvelope, pan: ModulationEnvelope, lfo: ChannelLfoSettings, };
