// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArpeggiatorSettings } from "./ArpeggiatorSettings";
import type { ChannelEnvelopes } from "./ChannelEnvelopes";
import type { NoteEchoSettings } from "./NoteEchoSettings";
import type { PolyphonySettings } from "./PolyphonySettings";

export type ChannelVoiceSettings = { arpeggiator: ArpeggiatorSettings, echo: NoteEchoSettings, polyphony: PolyphonySettings, envelopes: ChannelEnvelopes, };
