// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstrumentParams } from "./InstrumentParams";
import type { SamplerSettings } from "./SamplerSettings";

/**
 * What makes the sound of a channel: a sample or an instrument. Hosted
 * plugins are added as new variants.
 */
export type ChannelSource = { "type": "sampler" } & SamplerSettings | { "type": "instrument", 
/**
 * The instrument and its settings, with every value inside its
 * range.
 */
params: InstrumentParams, };
