// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { ChannelSource } from "./ChannelSource";
import type { ChannelTiming } from "./ChannelTiming";
import type { ChannelVoiceSettings } from "./ChannelVoiceSettings";
import type { TrackId } from "./TrackId";

/**
 * One row of the channel rack.
 */
export type Channel = { 
/**
 * Additional note generators and modulation; absent in older files.
 */
voice?: ChannelVoiceSettings, id: ChannelId, name: string, 
/**
 * Named rack group. The empty string is the ungrouped category.
 */
group?: string, 
/**
 * Non-destructive gate, shift and per-channel swing.
 */
timing?: ChannelTiming, 
/**
 * Display color as 0xRRGGBB.
 */
color: number, 
/**
 * Linear gain, 0 to [`MAX_GAIN`].
 */
volume: number, 
/**
 * -1 is hard left, 1 is hard right.
 */
pan: number, muted: boolean, solo: boolean, 
/**
 * The mixer track this channel plays into.
 */
mixerTrack: TrackId, source: ChannelSource, };
