// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelLfoShape } from "./ChannelLfoShape";
import type { LfoTarget } from "./LfoTarget";

export type ChannelLfoSettings = { enabled: boolean, shape: ChannelLfoShape, target: LfoTarget, rateHz: number, 
/**
 * Normalized bipolar amount. Full depth is 8 octaves / 2400 cents / 1 pan.
 */
depth: number, };
