// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelTiming = { 
/**
 * Scales the global swing, 0..=1. One preserves legacy playback.
 */
swingMix: number, 
/**
 * Maximum played note duration in ticks; zero leaves lengths unchanged.
 */
gateTicks: number, 
/**
 * Translation after swing, bounded to one quarter note in either direction.
 */
shiftTicks: number, };
