// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackId } from "./TrackId";
import type { ChannelTiming } from "./ChannelTiming";

export type ChannelPatch = { name?: string, group?: string, timing?: ChannelTiming, color?: number, volume?: number, pan?: number, muted?: boolean, solo?: boolean, mixerTrack?: TrackId, };
