// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelMuteParams = { 
/**
 * Silence the left channel; default false.
 */
left: boolean, 
/**
 * Silence the right channel; default false.
 */
right: boolean, };
