// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SamplerSettings } from "./SamplerSettings";

/**
 * What makes the sound of a channel. Synths and hosted plugins are added as
 * new variants.
 */
export type ChannelSource = { "type": "sampler" } & SamplerSettings;
