// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A boundary within one repeating Chop period. Gate scales the retained
 * piece (including partial edges); velocity multiplies the source dynamic.
 */
export type ChopStep = { tick: number, gate: number, velocity: number, };
