// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChorusParams = { 
/**
 * Minimum tap delay, 1..=30 ms; default 12.
 */
delayMs: number, 
/**
 * Sweep above the minimum, 0..=10 ms; default 4. Zero freezes delay.
 */
depthMs: number, 
/**
 * Independent tap rates, 0..=5 Hz; defaults 0.6, 0.8, 1.1.
 */
rate1Hz: number, rate2Hz: number, rate3Hz: number, 
/**
 * Right LFO offset in cycles, 0..=1; default 0.25 (90 degrees).
 */
stereoPhase: number, 
/**
 * Wet share, 0..=1; default 0.5. Zero is exact dry, one is wet only.
 */
mix: number, };
