// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Playback destination for audio clips. Direct prints retain their own gain,
 * pan, fades and playlist mute, and bypass all mixer strips and effects.
 */
export type ClipAudioOutput = "mixer" | "direct";
