// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipContent } from "./ClipContent";
import type { PlaylistTrackId } from "./PlaylistTrackId";

/**
 * A clip to add.
 */
export type ClipInit = { track: PlaylistTrackId, start: number, 
/**
 * Defaults to the natural length of the content: one pass of a pattern.
 */
length?: number, content: ClipContent, };
