// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipStretchQuality } from "./ClipStretchQuality";

/**
 * How a playlist audio clip changes time and pitch. Source files remain intact.
 */
export type ClipStretch = { "mode": "tape" } | { "mode": "spectral",
/**
 * Output duration divided by source duration, from 0.25 to 4.
 */
ratio: number, quality: ClipStretchQuality,
/**
 * Approximate voiced-spectrum formant preservation.
 */
formants: boolean, };
