// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationId } from "./AutomationId";
import type { PatternId } from "./PatternId";
import type { SampleId } from "./SampleId";
import type { TrackId } from "./TrackId";

/**
 * What a clip plays.
 */
export type ClipContent = { "type": "pattern", pattern: PatternId, } | { "type": "audio", 
/**
 * The audio to play. The sample cannot be removed from the pool
 * while a clip uses it.
 */
sample: SampleId, 
/**
 * The mixer track the clip plays into, through its effects, its
 * fader and its sends.
 */
mixerTrack: TrackId, 
/**
 * Linear gain, 0 to [`MAX_GAIN`].
 */
gain: number, 
/**
 * -1 is hard left, 1 is hard right.
 */
pan: number, 
/**
 * Length of the fade in, in ticks from the clip's start. At most
 * [`MAX_SONG_TICKS`]; one that is longer than the clip never
 * reaches full level.
 */
fadeIn: number, 
/**
 * Length of the fade out, in ticks before the clip's end. At most
 * [`MAX_SONG_TICKS`].
 */
fadeOut: number, 
/**
 * Plays the audio backwards, from its last frame.
 */
reverse: boolean, 
/**
 * Pitch in semitones, -48 to 48. It changes speed and pitch
 * together, like a tape: 12 plays an octave up in half the time.
 */
pitch: number, } | { "type": "automation", automation: AutomationId, };
