// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipContent } from "./ClipContent";
import type { ClipId } from "./ClipId";
import type { PlaylistTrackId } from "./PlaylistTrackId";

export type Clip = { id: ClipId, track: PlaylistTrackId, 
/**
 * Start on the timeline in ticks.
 */
start: number, 
/**
 * Length in ticks, at least 1.
 */
length: number, 
/**
 * How far into its content the clip starts, in ticks. A pattern clip
 * loops its pattern, so this is taken modulo the pattern length.
 */
offset: number, muted: boolean, content: ClipContent, };
