// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a clip plays.
 * Offline-prepared spectral quality for playlist audio clips.
 */
export type ClipStretchQuality = "fast" | "standard" | "high";
