// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipId } from "./ClipId";
import type { ClipPatch } from "./ClipPatch";

export type ClipUpdate = { id: ClipId, patch: ClipPatch, };
