// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternId } from "./PatternId";

/**
 * What a clip plays. Audio and automation clips are added as new variants.
 */
export type ClipContent = { "type": "pattern", pattern: PatternId, };
