// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relative tempo hypotheses, not calibrated probabilities. Half/double tempo can be ambiguous.
 */
export type ClipTempoCandidate = { bpm: number, confidence: number, };
