// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistTrackId } from "./PlaylistTrackId";

export type ClipPatch = { track?: PlaylistTrackId, start?: number, length?: number, offset?: number, muted?: boolean, };
