// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioClipUpdate } from "./AudioClipUpdate";
import type { AutomationId } from "./AutomationId";
import type { AutomationPatch } from "./AutomationPatch";
import type { AutomationPoint } from "./AutomationPoint";
import type { AutomationTarget } from "./AutomationTarget";
import type { ChannelId } from "./ChannelId";
import type { ChannelPatch } from "./ChannelPatch";
import type { ClipId } from "./ClipId";
import type { ClipInit } from "./ClipInit";
import type { ClipUpdate } from "./ClipUpdate";
import type { EffectId } from "./EffectId";
import type { EffectKind } from "./EffectKind";
import type { EffectParams } from "./EffectParams";
import type { EffectSlotPatch } from "./EffectSlotPatch";
import type { Envelope } from "./Envelope";
import type { InstrumentKind } from "./InstrumentKind";
import type { InstrumentParams } from "./InstrumentParams";
import type { MixerTrackPatch } from "./MixerTrackPatch";
import type { NoteId } from "./NoteId";
import type { NoteInit } from "./NoteInit";
import type { NoteUpdate } from "./NoteUpdate";
import type { PatternId } from "./PatternId";
import type { PatternPatch } from "./PatternPatch";
import type { PlaylistTrackId } from "./PlaylistTrackId";
import type { PlaylistTrackPatch } from "./PlaylistTrackPatch";
import type { SampleId } from "./SampleId";
import type { SamplePath } from "./SamplePath";
import type { SamplerPatch } from "./SamplerPatch";
import type { SettingsPatch } from "./SettingsPatch";
import type { TrackId } from "./TrackId";

export type Command = { "type": "updateSettings", patch: SettingsPatch, } | { "type": "addSample", name: string, path: SamplePath, } | { "type": "removeSample", id: SampleId, } | { "type": "addChannel", 
/**
 * Defaults to the sample name, the instrument's name, or "Sampler".
 */
name?: string, sample?: SampleId, 
/**
 * Makes the channel play this instrument, at its default settings.
 */
instrument?: InstrumentKind, 
/**
 * Position in the rack. Defaults to the end.
 */
index?: number, mixerTrack?: TrackId, } | { "type": "removeChannel", id: ChannelId, } | { "type": "duplicateChannel", id: ChannelId, } | { "type": "moveChannel", id: ChannelId, index: number, } | { "type": "updateChannel", id: ChannelId, patch: ChannelPatch, } | { "type": "setChannelSample", id: ChannelId, sample?: SampleId, } | { "type": "updateSampler", id: ChannelId, patch: SamplerPatch, } | { "type": "setSamplerEnvelope", id: ChannelId, envelope?: Envelope, } | { "type": "setInstrumentParam", channel: ChannelId, param: number, value: number, } | { "type": "setInstrumentParams", channel: ChannelId, params: InstrumentParams, } | { "type": "addPattern", 
/**
 * Defaults to "Pattern N".
 */
name?: string, } | { "type": "removePattern", id: PatternId, } | { "type": "duplicatePattern", id: PatternId, } | { "type": "movePattern", id: PatternId, index: number, } | { "type": "updatePattern", id: PatternId, patch: PatternPatch, } | { "type": "toggleStep", pattern: PatternId, channel: ChannelId, step: number, } | { "type": "addNotes", pattern: PatternId, channel: ChannelId, notes: Array<NoteInit>, } | { "type": "removeNotes", pattern: PatternId, channel: ChannelId, notes: Array<NoteId>, } | { "type": "updateNotes", pattern: PatternId, channel: ChannelId, updates: Array<NoteUpdate>, } | { "type": "clearLane", pattern: PatternId, channel: ChannelId, } | { "type": "addMixerTrack", 
/**
 * Defaults to "Insert N".
 */
name?: string, } | { "type": "removeMixerTrack", id: TrackId, } | { "type": "updateMixerTrack", id: TrackId, patch: MixerTrackPatch, } | { "type": "setTrackOutput", id: TrackId, output?: TrackId, } | { "type": "setSend", from: TrackId, to: TrackId, gain?: number, } | { "type": "addEffect", track: TrackId, kind: EffectKind, 
/**
 * Position in the chain. Defaults to the end.
 */
index?: number, } | { "type": "removeEffect", track: TrackId, effect: EffectId, } | { "type": "moveEffect", track: TrackId, effect: EffectId, toTrack?: TrackId, index: number, } | { "type": "updateEffect", track: TrackId, effect: EffectId, patch: EffectSlotPatch, } | { "type": "setEffectParam", track: TrackId, effect: EffectId, param: number, value: number, } | { "type": "setEffectParams", track: TrackId, effect: EffectId, params: EffectParams, } | { "type": "duplicateEffect", track: TrackId, effect: EffectId, } | { "type": "replaceEffect", track: TrackId, effect: EffectId, kind: EffectKind, } | { "type": "addPlaylistTrack", 
/**
 * Defaults to "Track N".
 */
name?: string, 
/**
 * Position among the playlist tracks. Defaults to the end.
 */
index?: number, } | { "type": "removePlaylistTrack", id: PlaylistTrackId, } | { "type": "updatePlaylistTrack", id: PlaylistTrackId, patch: PlaylistTrackPatch, } | { "type": "movePlaylistTrack", id: PlaylistTrackId, index: number, } | { "type": "addClips", clips: Array<ClipInit>, } | { "type": "removeClips", clips: Array<ClipId>, } | { "type": "updateClips", updates: Array<ClipUpdate>, } | { "type": "updateAudioClips", updates: Array<AudioClipUpdate>, } | { "type": "addAutomation", 
/**
 * Defaults to a name made from the target, which says what kind
 * of thing it is: "Kick volume" and "Kick pan" for a channel,
 * "Kick track volume" and "Kick track pan" for a mixer track,
 * "Kick to Bus send", "Bus Reverb mix" and "Bus Reverb Decay" for
 * an effect on the track Bus ("Bus Reverb 2 Decay" for the second
 * reverb of that track), "Lead Cutoff" for a setting of the
 * instrument on the channel Lead, and "Tempo". A name that an
 * automation already has is numbered: "Kick pan 2".
 */
name?: string, target: AutomationTarget, 
/**
 * The curve, checked as for [`Command::SetAutomationPoints`].
 * Defaults to one point at tick 0 with the value the target has
 * now, so that the automation changes nothing until it is drawn.
 */
points?: Array<AutomationPoint>, } | { "type": "removeAutomation", id: AutomationId, } | { "type": "updateAutomation", id: AutomationId, patch: AutomationPatch, } | { "type": "setAutomationPoints", id: AutomationId, points: Array<AutomationPoint>, } | { "type": "duplicateAutomation", id: AutomationId, } | { "type": "batch", 
/**
 * History label. Defaults to the label of the first command.
 */
label?: string, commands: Array<Command>, };
