// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectorMode } from "./DetectorMode";

/**
 * Settings of the [`Compressor`].
 */
export type CompressorParams = { 
/**
 * Use the track's detector-only key bus; silence when no key arrives.
 */
sidechain?: boolean, 
/**
 * Level above which the signal is turned down, in dB relative to full
 * scale. -60 to 0, default -18.
 */
thresholdDb: number, 
/**
 * How hard it is turned down: for every `ratio` dB the input rises
 * above the threshold, the output rises 1 dB. 1 (no compression) to
 * 100, default 4. At 100 the output never rises above the threshold.
 */
ratio: number, 
/**
 * How quickly the gain drops when the signal gets louder: the time to
 * complete 63% of the change, in ms. 0.05 to 250, default 10.
 */
attackMs: number, 
/**
 * How quickly the gain recovers when the signal gets quieter: the time
 * to complete 63% of the change, in ms. 5 to 2500, default 120.
 */
releaseMs: number, 
/**
 * Width in dB of the region around the threshold over which the ratio
 * eases in. 0 (a hard corner) to 24, default 6.
 */
kneeDb: number, 
/**
 * Gain applied after compression, in dB. -24 to 24, default 0.
 */
makeupDb: number, 
/**
 * Adds makeup gain that follows the threshold, ratio and knee: half of
 * what a full-scale signal is turned down by. Default off.
 */
autoMakeup: boolean, 
/**
 * How loudness is measured. Default peak.
 */
detector: DetectorMode, 
/**
 * Balance between the untouched input (0) and the compressed signal
 * (1). Values in between give parallel compression. Default 1.
 */
mix: number, };
