// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eight independent normalized controls, in a stable order.
 */
export type ControlSurfaceParams = { 
/**
 * Knob 1, 0 to 1; default 0.5.
 */
knob1: number, 
/**
 * Knob 2, 0 to 1; default 0.5.
 */
knob2: number, 
/**
 * Knob 3, 0 to 1; default 0.5.
 */
knob3: number, 
/**
 * Knob 4, 0 to 1; default 0.5.
 */
knob4: number, 
/**
 * Knob 5, 0 to 1; default 0.5.
 */
knob5: number, 
/**
 * Knob 6, 0 to 1; default 0.5.
 */
knob6: number, 
/**
 * Knob 7, 0 to 1; default 0.5.
 */
knob7: number, 
/**
 * Knob 8, 0 to 1; default 0.5.
 */
knob8: number, };
