// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConvolverParams = { 
/**
 * Mono IR shared by the independent stereo paths. Only impulse_length
 * samples are used. A zero length selects a unit impulse.
 */
impulse: number[], impulseLength: number, 
/**
 * Wet share, 0..1; dry receives the same 128-sample transport delay.
 */
mix: number, 
/**
 * Output linear gain, 0..4.
 */
gain: number, };
