// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurveLfoWave } from "./CurveLfoWave";

export type CurveLfo = { wave: CurveLfoWave, 
/**
 * Musical ticks per cycle.
 */
period: number, 
/**
 * Cycle fraction, zero through one.
 */
phase: number, 
/**
 * Center and bipolar amplitude in normalized target units.
 */
center: number, depth: number, 
/**
 * Fraction of each square-wave cycle spent high.
 */
width: number, seed: number, };
