// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How steeply a cut filter falls away past its corner.
 */
export type CutSlope = "db12" | "db24" | "db48";
