// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DcBlockParams = { 
/**
 * DC cutoff in Hz, 1 to 40; default 5. This is always a filter.
 */
cutoffHz: number, };
