// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the two channels' echoes relate.
 */
export type DelayMode = "stereo" | "pingPong";
