// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelayMode } from "./DelayMode";
import type { NoteDivision } from "./NoteDivision";

/**
 * Settings of the [`Delay`].
 */
export type DelayParams = { 
/**
 * Follow the tempo, using `division`, instead of `time_ms`. Default
 * on.
 */
sync: boolean, 
/**
 * Time between echoes in ms when not synced. 1 to 2000, default 250.
 */
timeMs: number, 
/**
 * Time between echoes as a note length when synced. Default an eighth
 * note. Times over 4 seconds, which only very slow tempos reach, are
 * held at 4 seconds.
 */
division: NoteDivision, 
/**
 * Share of each echo that is fed back to make the next one. 0 gives a
 * single echo; the maximum of 0.95 gives a very long trail that still
 * dies away. Default 0.35.
 */
feedback: number, 
/**
 * Whether echoes keep to their side or bounce between the sides.
 * Default stereo.
 */
mode: DelayMode, 
/**
 * Makes one side's echoes later than the other's, in ms, which widens
 * the sound. Positive values delay the right side, negative values the
 * left. -50 to 50, default 0.
 */
stereoOffsetMs: number, 
/**
 * Removes lows from each repeat, in Hz, so the trail thins out as it
 * goes. 20 to 2000, default 20.
 */
lowCutHz: number, 
/**
 * Removes highs from each repeat, in Hz, so the trail gets darker as
 * it goes, like tape. 500 to 20000, default 12000.
 */
highCutHz: number, 
/**
 * Grit added to each repeat. At 0 the echoes are clean; higher values
 * squash and warm them more with every pass. 0 to 1, default 0.
 */
saturation: number, 
/**
 * Balance between the dry input (0) and the echoes (1). Default 0.3.
 * Use 1 on a send track.
 */
mix: number, };
