// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the compressor measures loudness.
 */
export type DetectorMode = "peak" | "rms";
