// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPatch } from "./ProjectPatch";

/**
 * The result of dispatching a command.
 */
export type DispatchResult = { 
/**
 * Ids the command created, in the order its documentation gives.
 */
created: Array<number>, patch: ProjectPatch, };
