// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DistortionParams = { 
/**
 * Input drive in dB, 0 to 36; default 12.
 */
driveDb: number, 
/**
 * Rational saturation (0) through hard clipping (1); default 0.5.
 */
shape: number, 
/**
 * Output trim in dB, -24 to 0; default -6.
 */
outputDb: number, };
