// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryView } from "./HistoryView";
import type { Project } from "./Project";

/**
 * The whole document, sent when the UI starts and after a project loads.
 */
export type DocumentSnapshot = { revision: number, project: Project, history: HistoryView, dirty: boolean, 
/**
 * Path of the `.windfall` file, or `None` for a project never saved.
 */
path: string | null, };
