// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveStage } from "./DriveStage";

export type DriveStageParams = { 
/**
 * Stage algorithm; default bypass (which ignores stage gain).
 */
model: DriveStage, 
/**
 * Gain ahead of the nonlinearity in dB, -24..36; default 0.
 */
gainDb: number, };
