// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DriveStageParams } from "./DriveStageParams";

export type DriveChainParams = { 
/**
 * Signal flows through indices 0, 1, 2, then through output trim.
 */
stages: [DriveStageParams, DriveStageParams, DriveStageParams], 
/**
 * Output trim in dB, -24..12; default 0.
 */
outputDb: number, };
