// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A synthesis recipe, latched separately for each new hit.
 */
export type DrumMode = "kick" | "snare" | "hat" | "tom";
