// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrumMode } from "./DrumMode";

/**
 * Controls shared by four distinct recipes.
 */
export type DrumVoiceParams = { mode: DrumMode, 
/**
 * Tuning at MIDI 36, Hz, 30..2000, default 120. Kick body is half this.
 */
pitchHz: number, 
/**
 * Base duration, ms, 10..3000, default 500. Hat uses 25%, snare 60%.
 */
decayMs: number, 
/**
 * Brightness and modal balance, 0..1, default 0.5.
 */
tone: number, 
/**
 * Strike/wire/metal level according to recipe, 0..1, default 0.5.
 */
snap: number, 
/**
 * Linear output gain, 0..1, default 0.8.
 */
level: number, };
