// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One synthesized pad's independently editable patch.
 */
export type DrumPadParams = { 
/**
 * Fundamental, Hz, 30..2000, default 120. Pads do not track MIDI pitch.
 */
pitchHz: number, 
/**
 * Duration, ms, 10..4000, default 300.
 */
decayMs: number, 
/**
 * Modal balance and noise brightness, 0..1, default 0.5.
 */
tone: number, 
/**
 * Share of noise versus membrane modes, 0..1, default 0.1.
 */
noiseMix: number, };
