// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrumPadParams } from "./DrumPadParams";

/**
 * Sixteen patches and a master level. Keys 36..51 address `pads[0..16]`.
 */
export type DrumRackParams = { pads: [DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams, DrumPadParams], 
/**
 * Linear master gain, 0..1, default 0.8.
 */
level: number, };
