// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoFeedbackMode } from "./EchoFeedbackMode";
import type { EchoFilterParams } from "./EchoFilterParams";
import type { NoteDivision } from "./NoteDivision";

export type EchoUnitParams = { enabled: boolean, inputGain: number, inputPan: number, sync: boolean, timeMs: number, division: NoteDivision, stereoOffsetMs: number, feedback: number, feedbackMode: EchoFeedbackMode, feedbackPan: number, separation: number, filter: EchoFilterParams, filterPost: boolean, feedbackFilter: EchoFilterParams, outputGain: number, outputPan: number, 
/**
 * Signed send to the following unit; ignored and cleared for unit 7.
 */
nextSend: number, };
