// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoFilterMode } from "./EchoFilterMode";

export type EchoFilterParams = { mode: EchoFilterMode, frequencyHz: number, q: number, gainDb: number, gain: number, sections: number, };
