// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoUnitParams } from "./EchoUnitParams";

export type EchoBankParams = { dry: number, wet: number, inputGain: number, feedback: number, units: [EchoUnitParams, EchoUnitParams, EchoUnitParams, EchoUnitParams, EchoUnitParams, EchoUnitParams, EchoUnitParams, EchoUnitParams], };
