// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelNoteDivision } from "./ChannelNoteDivision";

export type EchoTime = { "unit": "milliseconds", ms: number, } | { "unit": "division", division: ChannelNoteDivision, };
