// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter order and response are independent of delay routing.
 */
export type EchoFilterMode = "off" | "lowpass" | "bandpass" | "notch" | "highpass" | "lowShelf" | "peak" | "highShelf";
