// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an effect on a mixer track. Unique across the whole
 * project, so an effect keeps its id when it moves to another track.
 */
export type EffectId = number;
