// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which effect an [`AnyEffect`] or an [`EffectParams`] holds.
 */
export type EffectKind = "eq" | "compressor" | "limiter" | "reverb" | "delay" | "balance" | "dcBlock" | "channelMute" | "polarity" | "stereoMatrix" | "softClipper" | "distortion";
