// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectId } from "./EffectId";
import type { EffectParams } from "./EffectParams";

/**
 * One effect on a mixer track.
 */
export type EffectSlot = { id: EffectId, 
/**
 * Off lets the signal pass untouched. Switching crossfades, so it
 * never clicks, and an effect that is off costs no CPU.
 */
enabled: boolean, 
/**
 * Balance between the untouched signal (0) and the effect's output
 * (1). A new effect starts at 1.
 */
mix: number, 
/**
 * Which effect this is and its settings, with every value inside its
 * range. The kind never changes for the life of the slot.
 */
params: EffectParams, };
