// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressorParams } from "./CompressorParams";
import type { DelayParams } from "./DelayParams";
import type { EqParams } from "./EqParams";
import type { LimiterParams } from "./LimiterParams";
import type { ReverbParams } from "./ReverbParams";

/**
 * The settings of any one effect. This is what a project stores for an
 * effect slot.
 */
export type EffectParams = { "type": "eq" } & EqParams | { "type": "compressor" } & CompressorParams | { "type": "limiter" } & LimiterParams | { "type": "reverb" } & ReverbParams | { "type": "delay" } & DelayParams;
