// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which effect an [`AnyEffect`] or an [`EffectParams`] holds.
 */
export type EffectKind = "eq" | "compressor" | "limiter" | "reverb" | "delay" | "balance" | "dcBlock" | "channelMute" | "polarity" | "stereoMatrix" | "softClipper" | "distortion" | "fastLowpass" | "selectableFilter" | "bassShelf" | "lofi" | "chorus" | "flanger" | "phaser" | "bandSplit" | "multibandCompressor" | "multibandMaximizer" | "transientShaper" | "transientSplit" | "oneKnob" | "bassHarmonics" | "exciter" | "waveshaper" | "overdrive" | "guitarRack" | "driveChain" | "vintageChorus" | "hyperChorus" | "vintagePhaser" | "stackedFlanger" | "bandDelay" | "room" | "spreader" | "stereoEnhancer" | "volumeGate" | "timeTransport" | "scratch" | "performanceRack" | "convolver" | "frequencyShifter" | "pitchShift" | "pitchCorrect" | "vocoder" | "echoBank" | "frequencyDelay" | "sevenBand" | "morphEq" | "filterBank" | "xyPad" | "xyzPad" | "panLfo" | "envelopeFollower" | "noteEnvelope" | "lushSpace" | "tuner" | "stageStack" | "controlSurface" | "sendTap";
