// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceParams } from "./BalanceParams";
import type { ChannelMuteParams } from "./ChannelMuteParams";
import type { CompressorParams } from "./CompressorParams";
import type { DcBlockParams } from "./DcBlockParams";
import type { DelayParams } from "./DelayParams";
import type { DistortionParams } from "./DistortionParams";
import type { EqParams } from "./EqParams";
import type { LimiterParams } from "./LimiterParams";
import type { PolarityParams } from "./PolarityParams";
import type { ReverbParams } from "./ReverbParams";
import type { SoftClipperParams } from "./SoftClipperParams";
import type { StereoMatrixParams } from "./StereoMatrixParams";

/**
 * The settings of any one effect. This is what a project stores for an
 * effect slot.
 */
export type EffectParams = { "type": "eq" } & EqParams | { "type": "compressor" } & CompressorParams | { "type": "limiter" } & LimiterParams | { "type": "reverb" } & ReverbParams | { "type": "delay" } & DelayParams | { "type": "balance" } & BalanceParams | { "type": "dcBlock" } & DcBlockParams | { "type": "channelMute" } & ChannelMuteParams | { "type": "polarity" } & PolarityParams | { "type": "stereoMatrix" } & StereoMatrixParams | { "type": "softClipper" } & SoftClipperParams | { "type": "distortion" } & DistortionParams;
