// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineStatus = { 
/**
 * An output stream is open and running.
 */
running: boolean, 
/**
 * Driver family, such as "WASAPI", "ASIO" or "CoreAudio".
 */
host: string, device: string | null, sampleRate: number, 
/**
 * Frames per audio callback.
 */
bufferFrames: number, 
/**
 * Output latency of one buffer in milliseconds.
 */
latencyMs: number, 
/**
 * Why the stream is not running, when it is not.
 */
error: string | null, };
