// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvelopeFollowerParams = { attackMs: number, releaseMs: number, inputGain: number, base: number, amount: number, duck: number, lfoDepth: number, rateHz: number, };
