// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attack, decay, sustain, release volume envelope. The three times run
 * from 0 to [`MAX_ENVELOPE_MS`].
 */
export type Envelope = { attackMs: number, decayMs: number, 
/**
 * Sustain level, 0 to 1.
 */
sustain: number, releaseMs: number, };
