// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attack, decay, sustain, release envelope.
 */
export type EnvelopeParams = { 
/**
 * Time to rise to full level after a key goes down, in ms. 0 to
 * 10000.
 */
attackMs: number, 
/**
 * Time to fall from full level to the sustain level, in ms. 1 to
 * 10000.
 */
decayMs: number, 
/**
 * Level held while the key stays down, 0 to 1.
 */
sustain: number, 
/**
 * Time to fall to silence after the key is let go, in ms. 1 to 10000.
 */
releaseMs: number, };
