// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A shelf or bell band of the equaliser.
 */
export type EqBand = { 
/**
 * A band that is off leaves the signal alone.
 */
enabled: boolean, 
/**
 * Centre of a bell, or corner of a shelf, in Hz. 20 to 20000.
 */
frequencyHz: number, 
/**
 * Boost or cut in dB. -24 to 24, default 0.
 */
gainDb: number, 
/**
 * Sharpness. For a bell, higher is narrower: 0.1 to 18, default 1.
 * For a shelf, 0.707 is the smoothest slope and higher values add a
 * bump before the shelf: 0.1 to 2, default 0.707.
 */
q: number, };
