// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CutSlope } from "./CutSlope";

/**
 * The low cut or high cut band of the equaliser.
 */
export type EqCutBand = { 
/**
 * Off by default.
 */
enabled: boolean, 
/**
 * The corner in Hz, where the filter is 3 dB down at the default Q.
 * 20 to 20000.
 */
frequencyHz: number, 
/**
 * Resonance at the corner. 0.707 is flat right up to the corner;
 * higher values add a peak there. 0.25 to 8, default 0.707.
 */
q: number, 
/**
 * How steeply the filter falls. Default 12 dB per octave.
 */
slope: CutSlope, };
