// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBand } from "./EqBand";
import type { EqCutBand } from "./EqCutBand";

/**
 * Settings of the [`ParametricEq`]. The defaults change nothing.
 */
export type EqParams = { 
/**
 * Removes everything below its corner. Default 30 Hz, off.
 */
lowCut: EqCutBand, 
/**
 * Boosts or cuts everything below its corner. Default 100 Hz.
 */
lowShelf: EqBand, 
/**
 * A bell. Default 400 Hz.
 */
peak1: EqBand, 
/**
 * A bell. Default 1 kHz.
 */
peak2: EqBand, 
/**
 * A bell. Default 3.5 kHz.
 */
peak3: EqBand, 
/**
 * Boosts or cuts everything above its corner. Default 8 kHz.
 */
highShelf: EqBand, 
/**
 * Removes everything above its corner. Default 18 kHz, off.
 */
highCut: EqCutBand, 
/**
 * Gain applied after all bands, in dB. -24 to 24, default 0.
 */
outputGainDb: number, };
