// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExciterParams = { frequencyHz: number, drive: number, mix: number, color: number, };
