// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackId } from "./TrackId";

/**
 * One file an export wrote.
 */
export type ExportedFile = { 
/**
 * Absolute path of the file.
 */
path: string, 
/**
 * The mixer track the file is the stem of. `None` for the mix.
 */
track: TrackId | null, 
/**
 * Length of the audio in frames, at the export's sample rate.
 */
frames: number, 
/**
 * Size of the file in bytes.
 */
bytes: number, };
