// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitDepth } from "./BitDepth";
import type { ExportFormat } from "./ExportFormat";
import type { PlayMode } from "./PlayMode";

export type ExportOptions = { 
/**
 * Absolute path of the file to write.
 */
path: string, format: ExportFormat, bitDepth: BitDepth, sampleRate: number, 
/**
 * Pattern mode renders the transport's pattern `pattern_loops` times.
 * Song mode renders the playlist from the start to the last clip's end.
 */
mode: PlayMode, patternLoops: number, 
/**
 * Extra time rendered after the end so reverb and release tails finish.
 * With `auto_tail` it is the longest the tail may get.
 */
tailSecs: number, 
/**
 * Ends the tail as soon as everything has rung out: every note, every
 * instrument and every effect is done and the output has fallen
 * silent. The file is then as long as the sound, up to `tail_secs`
 * past the end. Without it the tail is always `tail_secs` long.
 */
autoTail: boolean, };
