// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportProgress = { path: string, 
/**
 * 0 to 1.
 */
fraction: number, done: boolean, error: string | null, };
