// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StemMode } from "./StemMode";
import type { TrackId } from "./TrackId";

/**
 * Exports the mixer tracks apart, each to a file of its own.
 */
export type ExportStems = { mode: StemMode, 
/**
 * The mixer tracks to export. Absent means every track that has
 * something to give: with `trackOutputs` every track a channel or an
 * audio clip plays into, straight or by way of other tracks, and with
 * `toMaster` every track one plays straight into. The master cannot
 * be listed; its sound is the mix.
 */
tracks?: Array<TrackId>, 
/**
 * Writes the whole mix as well, as one more file.
 */
includeMix: boolean, 
/**
 * Puts each track's place in the mixer in front of its name, as in
 * "03 Bass", so the files sort the way the mixer shows the tracks.
 */
numbered: boolean, 
/**
 * Puts the files in a folder of their own, named like the export.
 * Without it they are written where the export's path points.
 */
folder: boolean, };
