// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitDepth } from "./BitDepth";
import type { ExportFormat } from "./ExportFormat";
import type { ExportStems } from "./ExportStems";
import type { Mp3Settings } from "./Mp3Settings";
import type { PlayMode } from "./PlayMode";
import type { TickRange } from "./TickRange";

export type ExportOptions = { 
/**
 * Optional linear once-only song region; absent retains whole-song export.
 */
region?: TickRange, 
/**
 * Optional selected-export source guard, checked before snapshot preparation.
 */
regionGeneration?: number, regionRevision?: number, 
/**
 * Absolute path of the file to write. With `stems` no file of this
 * name is written: for `Song.flac` the files are `Song - Mix.flac`,
 * `Song - Bass.flac` and so on, in a folder `Song` beside it or,
 * without `stems.folder`, where `Song.flac` would have been.
 */
path: string, format: ExportFormat, 
/**
 * Used by WAV and FLAC. FLAC has no 32-bit float.
 */
bitDepth: BitDepth, sampleRate: number, 
/**
 * Pattern mode renders the transport's pattern `pattern_loops` times.
 * Song mode renders the playlist from the start to the last clip's end.
 */
mode: PlayMode, patternLoops: number, 
/**
 * Extra time rendered after the end so reverb and release tails finish.
 * With `auto_tail` it is the longest the tail may get.
 */
tailSecs: number, 
/**
 * Ends the tail as soon as everything has rung out: every note, every
 * instrument and every effect is done and the output has fallen
 * silent. The file is then as long as the sound, up to `tail_secs`
 * past the end. Without it the tail is always `tail_secs` long.
 */
autoTail: boolean, 
/**
 * FLAC compression level, 0 to 8. Every level is lossless; a higher
 * one takes longer and gives a slightly smaller file. Absent means 5.
 */
flacLevel?: number, 
/**
 * Vorbis quality from -1 to 10. Absent means 6.
 */
oggQuality?: number, 
/**
 * MP3 rate and channel coding; absent means 192 kbit/s joint stereo.
 */
mp3?: Mp3Settings, 
/**
 * Exports stems instead of one file. Absent means one file, the mix.
 */
stems?: ExportStems, };
