// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BitDepth } from "./BitDepth";
import type { ExportFormat } from "./ExportFormat";
import type { PlayMode } from "./PlayMode";

export type ExportOptions = { 
/**
 * Absolute path of the file to write.
 */
path: string, format: ExportFormat, bitDepth: BitDepth, sampleRate: number, 
/**
 * Pattern mode renders the transport's pattern `pattern_loops` times.
 * Song mode renders the playlist from the start to the last clip's end.
 */
mode: PlayMode, patternLoops: number, 
/**
 * Extra time rendered after the end so reverb and release tails finish.
 */
tailSecs: number, };
