// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalOutputRoute = { left: number, 
/**
 * None folds stereo to mono on `left`.
 */
right: number | null, 
/**
 * Suppress the ordinary output edge; explicit sends remain available.
 */
exclusive: boolean, };
