// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FastLowpassParams = { 
/**
 * Cutoff in Hz, 20..=20000; default 20000. Limited to 0.49 * rate.
 */
cutoffHz: number, 
/**
 * Q, 0.5..=10; default 1/sqrt(2). Gain at the cutoff equals Q.
 */
q: number, };
