// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterRouting } from "./FilterRouting";
import type { FilterSlotParams } from "./FilterSlotParams";

export type FilterBankParams = { 
/**
 * Eight independent stereo filter slots; all bypassed by default.
 */
slots: [FilterSlotParams, FilterSlotParams, FilterSlotParams, FilterSlotParams, FilterSlotParams, FilterSlotParams, FilterSlotParams, FilterSlotParams], 
/**
 * Serial cascades all slots. Parallel averages the active branches.
 */
routing: FilterRouting, };
