// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterMode } from "./FilterMode";
import type { FilterSlope } from "./FilterSlope";

/**
 * Settings of the synth's filter.
 */
export type FilterParams = { 
/**
 * Default low-pass.
 */
mode: FilterMode, 
/**
 * Default 12 dB per octave.
 */
slope: FilterSlope, 
/**
 * Cutoff in Hz, before key tracking, envelope, velocity and LFOs move
 * it. 20 to 20000, default 20000 (fully open).
 */
cutoffHz: number, 
/**
 * Emphasis at the cutoff, 0 to 1. At 0 there is none; toward 1 the
 * filter rings and whistles. Default 0.1.
 */
resonance: number, 
/**
 * How much the cutoff follows the key played, around middle C. At 1 it
 * moves an octave per octave, so every note is equally bright. 0 to
 * 1, default 0.
 */
keyTracking: number, 
/**
 * How far the filter envelope moves the cutoff at its peak, in
 * octaves. Negative values close the filter instead. -8 to 8, default
 * 0.
 */
envelopeOctaves: number, 
/**
 * How much playing softly closes the filter. At 1 the softest note is
 * four octaves darker than the hardest. 0 to 1, default 0.
 */
velocity: number, 
/**
 * Overdrive before the filter. 0 is clean; higher values are louder,
 * fuller and grittier. 0 to 1, default 0.
 */
drive: number, };
