// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How steeply the synth's filter falls away past the cutoff.
 */
export type FilterSlope = "db12" | "db24";
