// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSlotMode } from "./FilterSlotMode";

export type FilterSlotParams = { mode: FilterSlotMode, 
/**
 * Corner or center in Hz, 20 to 20,000; clamped below Nyquist.
 */
frequencyHz: number, 
/**
 * Resonance Q, 0.1 to 10; default 1/sqrt(2).
 */
q: number, };
