// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which part of the spectrum the synth's filter lets through.
 */
export type FilterMode = "lowPass" | "bandPass" | "highPass";
