// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls for [`super::FingerBass`], including two physical body peaks.
 */
export type FingerBassParams = { 
/**
 * Nominal decay, 0.1–8 seconds; default 1.8.
 */
decaySeconds: number, 
/**
 * String and body tone, 0–1; default 0.45.
 */
tone: number, 
/**
 * Extra loop loss, 0–1; default 0.25.
 */
damping: number, 
/**
 * Amount of the body bandpasses, 0–1; default 0.6.
 */
body: number, 
/**
 * Excitation position, 0.05–0.95; default 0.18.
 */
pickPosition: number, 
/**
 * Output gain, 0–1; default 0.8.
 */
level: number, };
