// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlangerParams = { 
/**
 * Minimum delay, 0.1..=10 ms; default 1. At least one frame at any rate.
 */
delayMs: number, 
/**
 * Sweep above the minimum, 0..=10 ms; default 3.
 */
depthMs: number, 
/**
 * Free-running rate, 0..=5 Hz; default 0.25. Zero freezes phase.
 */
rateHz: number, 
/**
 * Right-channel phase offset, cycles 0..=1; default 0.25.
 */
stereoPhase: number, 
/**
 * Signed feedback, -0.9..=0.9; default 0.5.
 */
feedback: number, 
/**
 * Feedback/wet lowpass amount, 0..=1; default 0.2. Pole is 0.9 * damping.
 */
damping: number, 
/**
 * Sine-to-triangle blend, 0..=1; default 0.
 */
shape: number, 
/**
 * Invert the wet output independently of the feedback sign; default false.
 */
invertWet: boolean, 
/**
 * Wet share, 0..=1; default 0.5.
 */
mix: number, };
