// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlpMissingSample } from "./FlpMissingSample";
import type { ImportReport } from "./ImportReport";

/**
 * A prepared import. Its token opens exactly this checked conversion.
 */
export type FlpImportPreview = { token: number, name: string, report: ImportReport, warnings: Array<string>, missingSamples: Array<FlpMissingSample>, retainedPlugins: number, };
