// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional folders supplied by the user; Windfall ships no FL Studio content.
 */
export type FlpImportOptions = { factoryDataDir: string | null, userDataDir: string | null, sampleSearchFolders: Array<string>, };
