// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleId } from "./SampleId";

/**
 * A missing or unreadable sample, with its identity for later recovery.
 */
export type FlpMissingSample = { sample: SampleId, name: string, path: string, };
