// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Linear attack, decay, sustain and release. Times are milliseconds.
 */
export type FmEnvelopeParams = { attackMs: number, decayMs: number, sustain: number, releaseMs: number, };
