// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FmEnvelopeParams } from "./FmEnvelopeParams";

/**
 * Sine operator. Level scales both carrier output and modulation depth.
 */
export type FmOperatorParams = { ratio: number, level: number, envelope: FmEnvelopeParams, };
