// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FmOperatorParams } from "./FmOperatorParams";
import type { FourOpAlgorithm } from "./FourOpAlgorithm";

export type FourOpParams = { algorithm: FourOpAlgorithm, 
/**
 * Operator 4 self-modulation, in radians at unit operator level.
 */
feedback: number, operators: [FmOperatorParams, FmOperatorParams, FmOperatorParams, FmOperatorParams], gain: number, };
