// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eight acyclic graphs; operator numbers in these names are one-based.
 */
export type FourOpAlgorithm = "stack" | "pairs" | "fanIn" | "fanOut" | "branch" | "merge" | "triple" | "parallel";
