// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrequencyShifterParams = { 
/**
 * Additive frequency translation, -5000..5000 Hz. Positive shifts up.
 */
shiftHz: number, mix: number, };
