// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FrequencyBandParams = { 
/**
 * Milliseconds before scaling, 0..1000; default zero.
 */
delayMs: number, 
/**
 * Linear gain, 0..1; default unity.
 */
level: number, 
/**
 * Stereo balance, -1..1; default center.
 */
pan: number, 
/**
 * False passes the undelayed band; history remains live.
 */
enabled: boolean, };
