// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrequencyBandParams } from "./FrequencyBandParams";
import type { FrequencySplit } from "./FrequencySplit";

export type FrequencyDelayParams = { dry: number, wet: number, feedback: number, scale: number, shortRange: boolean, bandwidth: number, split: FrequencySplit, bands: [FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams, FrequencyBandParams], };
