// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectId } from "./EffectId";

/**
 * The reading of one compressor's or limiter's gain reduction meter.
 */
export type GainReduction = { effect: EffectId, 
/**
 * The deepest reduction since the last frame, in dB: 0 means the
 * signal was not turned down, 6 means it was turned down by 6 dB.
 */
db: number, };
