// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleTable } from "./SampleTable";

/**
 * Grain Cloud parameters. Table frames are source data, not automatable controls.
 */
export type GrainCloudParams = { table: SampleTable, rootKey: number, grainSizeMs: number, density: number, position: number, spray: number, pitch: number, seed: number, level: number, releaseMs: number, };
