// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuitarModel = "cleanBoost" | "tubeSoftClip" | "hardFuzz" | "octaveUp" | "trebleBooster" | "midScoop" | "wah" | "compressorSquash" | "gate" | "springSlap" | "cabinet";
