// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuitarModel } from "./GuitarModel";

export type GuitarRackParams = { 
/**
 * One of eleven algorithms; default clean boost.
 */
model: GuitarModel, 
/**
 * Input gain in dB, 0..36; default 6.
 */
driveDb: number, 
/**
 * Output trim in dB, -24..12; default -6.
 */
outputDb: number, };
