// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartialGains } from "./PartialGains";
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`HarmonicStack`].
 */
export type HarmonicStackParams = { 
/**
 * How many harmonics are sounded, counting the fundamental. 1 to 64,
 * default 16. Each one costs a sine per sample per note.
 */
partials: number, 
/**
 * Which half of the harmonics is favoured. At -1 only the odd ones
 * sound, which is hollow and clarinet-like; at 1 only the even ones,
 * which is the same series an octave up. -1 to 1, default 0.
 */
oddEvenTilt: number, 
/**
 * How much quieter each harmonic is than the one below, on top of the
 * levels set for them. 0 leaves them alone; 1 takes 24 dB off every
 * octave of frequency. 0 to 1, default 0.
 */
rolloff: number, 
/**
 * The level of each harmonic, 0 to 1 each. The default is the
 * spectrum of a saw.
 */
gains: PartialGains, voicing: VoicingParams, };
