// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

/**
 * The undo history as the UI shows it.
 */
export type HistoryView = { 
/**
 * Oldest first.
 */
entries: Array<HistoryEntry>, 
/**
 * How many entries are currently applied. Entries at or past this index
 * have been undone and can be redone.
 */
cursor: number, };
