// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryEntry = { 
/**
 * What the edit did, in words a menu can show, such as "Add channel".
 */
label: string, };
