// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportCategory } from "./ReportCategory";

/**
 * What an import did.
 */
export type ImportReport = { 
/**
 * The version of FL Studio that saved the file, as the file gives it.
 */
flVersion?: string, 
/**
 * The time base of the file, in ticks per quarter note.
 */
sourcePpq: number, 
/**
 * Every section, in the order of [`ReportSection::ALL`], including
 * the ones with nothing in them.
 */
categories: Array<ReportCategory>, 
/**
 * The ids of events in the file that no source this importer is built
 * on knows. Their data was skipped. A long list means the file comes
 * from a version of FL Studio newer than the importer.
 */
unknownEventIds: Array<number>, 
/**
 * What went wrong while the file was being read: a cut-off file, a
 * part that did not add up.
 */
readProblems: Array<string>, };
