// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`Inharmonic`].
 */
export type InharmonicParams = { 
/**
 * How many partials are sounded, counting the lowest. 1 to 64,
 * default 24.
 */
partials: number, 
/**
 * How much the partials spread apart as they climb. At 0 the series is
 * close to a harmonic one and sounds like a struck string; toward 1 it
 * opens out into a bell. 0 to 1, default 0.35.
 */
stiffness: number, 
/**
 * Bends the whole series by a power of the partial number, which no
 * amount of stiffness can do: it moves the low partials as well as the
 * high ones. 0.02 to 0.3, default 0.08.
 */
stretch: number, 
/**
 * How much quieter each partial is than the one below. 0 is a flat
 * spectrum; 1 takes 24 dB off every octave of frequency. 0 to 1,
 * default 0.3.
 */
rolloff: number, voicing: VoicingParams, };
