// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMonitorTrackInfo } from "./InputMonitorTrackInfo";

/**
 * Runtime-only standalone input monitoring. Saved routes belong to the mixer.
 */
export type InputMonitorState = { active: boolean, sampleRate: number, tracks: Array<InputMonitorTrackInfo>, error: string | null, };
