// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingAlignmentStatus } from "./RecordingAlignmentStatus";
import type { RecordingMonitorStatus } from "./RecordingMonitorStatus";
import type { TrackId } from "./TrackId";

export type InputMonitorTrackInfo = { mixerTrack: TrackId, name: string, alignment: RecordingAlignmentStatus, monitor: RecordingMonitorStatus, };
