// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SynthParams } from "./SynthParams";

/**
 * The settings of any one instrument. This is what a project stores for
 * an instrument channel.
 */
export type InstrumentParams = { "type": "subtractiveSynth" } & SynthParams;
