// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which instrument an [`AnyInstrument`] or an [`InstrumentParams`] holds.
 */
export type InstrumentKind = "subtractiveSynth" | "fourOp" | "matrixFm" | "ringHybrid" | "harmonicStack" | "partialMorph" | "inharmonic" | "resynth" | "seedPatch" | "scanSynth" | "pluck" | "fingerBass" | "acousticString" | "membrane" | "drumRack" | "kick" | "drumVoice" | "sliceMap" | "sliceDeck" | "grainCloud" | "waveRide" | "acidLine" | "tripleOsc" | "waveLane" | "macroVoice" | "speechVoice";
