// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcidLineParams } from "./AcidLineParams";
import type { AcousticStringParams } from "./AcousticStringParams";
import type { DrumRackParams } from "./DrumRackParams";
import type { DrumVoiceParams } from "./DrumVoiceParams";
import type { FingerBassParams } from "./FingerBassParams";
import type { FourOpParams } from "./FourOpParams";
import type { GrainCloudParams } from "./GrainCloudParams";
import type { HarmonicStackParams } from "./HarmonicStackParams";
import type { InharmonicParams } from "./InharmonicParams";
import type { KickParams } from "./KickParams";
import type { MacroVoiceParams } from "./MacroVoiceParams";
import type { MatrixFmParams } from "./MatrixFmParams";
import type { MembraneParams } from "./MembraneParams";
import type { PartialMorphParams } from "./PartialMorphParams";
import type { PluckParams } from "./PluckParams";
import type { ResynthParams } from "./ResynthParams";
import type { RingHybridParams } from "./RingHybridParams";
import type { ScanSynthParams } from "./ScanSynthParams";
import type { SeedPatchParams } from "./SeedPatchParams";
import type { SliceDeckParams } from "./SliceDeckParams";
import type { SliceMapParams } from "./SliceMapParams";
import type { SpeechVoiceParams } from "./SpeechVoiceParams";
import type { SynthParams } from "./SynthParams";
import type { TripleOscParams } from "./TripleOscParams";
import type { WaveLaneParams } from "./WaveLaneParams";
import type { WaveRideParams } from "./WaveRideParams";

/**
 * The settings of any one instrument. This is what a project stores for
 * an instrument channel.
 */
export type InstrumentParams = { "type": "subtractiveSynth" } & SynthParams | { "type": "fourOp" } & FourOpParams | { "type": "matrixFm" } & MatrixFmParams | { "type": "ringHybrid" } & RingHybridParams | { "type": "harmonicStack" } & HarmonicStackParams | { "type": "partialMorph" } & PartialMorphParams | { "type": "inharmonic" } & InharmonicParams | { "type": "resynth" } & ResynthParams | { "type": "seedPatch" } & SeedPatchParams | { "type": "scanSynth" } & ScanSynthParams | { "type": "pluck" } & PluckParams | { "type": "fingerBass" } & FingerBassParams | { "type": "acousticString" } & AcousticStringParams | { "type": "membrane" } & MembraneParams | { "type": "drumRack" } & DrumRackParams | { "type": "kick" } & KickParams | { "type": "drumVoice" } & DrumVoiceParams | { "type": "sliceMap" } & SliceMapParams | { "type": "sliceDeck" } & SliceDeckParams | { "type": "grainCloud" } & GrainCloudParams | { "type": "waveRide" } & WaveRideParams | { "type": "acidLine" } & AcidLineParams | { "type": "tripleOsc" } & TripleOscParams | { "type": "waveLane" } & WaveLaneParams | { "type": "macroVoice" } & MacroVoiceParams | { "type": "speechVoice" } & SpeechVoiceParams;
