// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Add `pitch_semitones` to the destination's pitch and `gain_offset` to
 * unity gain. Pitch is -302..302 semitones; gain offset is -1..0.
 */
export type KeyboardControl = { pitchSemitones: number, gainOffset: number, };
