// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls for the fast swept kick.
 */
export type KickParams = { 
/**
 * Settled body pitch at MIDI 36, Hz, 20..250, default 52.
 */
pitchHz: number, 
/**
 * Body duration, ms, 10..1500, default 420.
 */
decayMs: number, 
/**
 * Initial pitch above the body, semitones, 0..60, default 36.
 */
pitchDropSemitones: number, 
/**
 * Pitch sweep time constant, ms, 1..150, default 18.
 */
pitchDecayMs: number, 
/**
 * Filtered 2 ms click level, 0..1, default 0.25.
 */
click: number, 
/**
 * Linear output gain, 0..1, default 0.8.
 */
level: number, };
