// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { Note } from "./Note";

/**
 * The notes one channel plays in one pattern.
 */
export type Lane = { channel: ChannelId, 
/**
 * Sorted by `start`, then `key`, then `id`.
 */
notes: Array<Note>, };
