// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LfoShape } from "./LfoShape";

/**
 * Settings of one LFO of the synth. The LFOs run freely and are shared by
 * all voices.
 */
export type LfoParams = { 
/**
 * Default sine.
 */
shape: LfoShape, 
/**
 * Speed in Hz. 0.01 to 30, default 5.
 */
rateHz: number, 
/**
 * How far it bends the pitch at its extremes, in semitones: vibrato.
 * -24 to 24, default 0.
 */
pitchSemitones: number, 
/**
 * How far it moves the filter cutoff at its extremes, in octaves.
 * -5 to 5, default 0.
 */
cutoffOctaves: number, 
/**
 * How much it dips the volume: tremolo. 0 to 1, default 0.
 */
amp: number, 
/**
 * How far it moves the pulse width of every oscillator. -0.45 to
 * 0.45, default 0.
 */
pulseWidth: number, };
