// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape of one LFO cycle. Every shape swings between -1 and 1.
 */
export type LfoShape = "sine" | "triangle" | "saw" | "square" | "random";
