// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibrarySearch = { query: string, favoritesOnly: boolean, tags: Array<string>, };
