// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserEntry } from "./BrowserEntry";
import type { LibraryFileToken } from "./LibraryFileToken";
import type { LibraryMetadata } from "./LibraryMetadata";

export type LibraryEntry = { entry: BrowserEntry, relativePath: string, token: LibraryFileToken, metadata: LibraryMetadata, };
