// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryEntry } from "./LibraryEntry";
import type { LibraryStatus } from "./LibraryStatus";

export type LibraryResults = { generation: number, status: LibraryStatus, indexed: number, examined: number, entries: Array<LibraryEntry>, truncated: boolean, resultsTruncated: boolean, issues: Array<string>, availableTags: Array<string>, 
/**
 * Present in the simulator, which searches fixtures rather than the user's disk.
 */
limitation: string | null, };
