// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A result's file version and root membership. Never a permission to bypass the loader.
 */
export type LibraryFileToken = { path: string, rootPath: string, generation: number, fingerprint: string, };
