// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings of the [`Limiter`].
 */
export type LimiterParams = { 
/**
 * The level no output sample exceeds, in dB relative to full scale.
 * -24 to 0, default -0.3.
 */
ceilingDb: number, 
/**
 * Gain applied before limiting, in dB. Turning it up drives the signal
 * into the ceiling and makes it louder. -12 to 24, default 0.
 */
inputGainDb: number, 
/**
 * How quickly the gain recovers after a peak has passed: the time to
 * complete 63% of the recovery, in ms. 1 to 1000, default 100. Short
 * times are louder but can distort bass; long times are cleaner but
 * can duck the signal audibly after a loud hit.
 */
releaseMs: number, 
/**
 * How far ahead the limiter looks, in ms, which is also how long it
 * delays the signal. 0.1 to 20, default 5. Longer look-ahead turns
 * down more gently before a peak arrives and so distorts less.
 */
lookaheadMs: number, };
