// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterPlacement } from "./FilterPlacement";
import type { RunRelation } from "./RunRelation";

export type LofiParams = { 
/**
 * Symmetric midtread resolution, 2..=16 bits; default 8.
 */
bits: number, 
/**
 * Blend from unquantized to quantized, 0..=1; default 1.
 */
quantize: number, 
/**
 * Host rate / capture rate, 1..=64; default 4. Fractional ratios work.
 */
rateRatio: number, 
/**
 * Drive before rational saturation, 0..=36 dB; default 6.
 */
driveDb: number, 
/**
 * Blend from original to driven saturation, 0..=1; default 0.25.
 */
distortion: number, 
/**
 * Tone cutoff frequency, 20..=20000 Hz; default 8000.
 * Effective frequency is capped at 0.45 * prepared sample rate.
 */
cutoffHz: number, 
/**
 * Blend from unfiltered to tone-filtered audio, 0..=1; default 1.
 */
filter: number, 
/**
 * Dry/wet blend, 0..=1; default 1. Histories keep running when dry.
 */
mix: number, 
/**
 * Final dry-and-wet trim, -24..=12 dB; default -3.
 */
outputDb: number, 
/**
 * Unreplaced run duration, 0..=1000 ms; default 10.
 */
preserveMs: number, 
/**
 * Independent replaced run duration, 0..=1000 ms; default 2.
 */
replaceMs: number, 
/**
 * Replaced duration independent/equal/double/half of the preserved run.
 */
runRelation: RunRelation, 
/**
 * Fixed positive nominal amplitude during replaced runs, 0..=1; default 0.
 */
replacementValue: number, 
/**
 * Blend toward the fixed value during replaced runs, 0..=1; default 0.
 */
replacement: number, 
/**
 * Morph from monotonic tone to resonant lowpass, 0..=1; default 0.
 * The resonant path's Q increases from 1/sqrt(2) to 4.
 */
resonance: number, 
/**
 * Tone filter before or after drive/quantization/replacement/hold.
 */
placement: FilterPlacement, };
