// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings of [`LushSpace`]. Decay is nominal low-frequency RT60.
 */
export type LushSpaceParams = { 
/**
 * Seconds, 0..8, default 3.5. Zero selects a short 0.18 second decay.
 */
decayS: number, 
/**
 * Milliseconds before the hall input, 0..120, default 20.
 */
preDelayMs: number, 
/**
 * High-frequency loss in the feedback loop, 0..1, default 0.45.
 */
damping: number, 
/**
 * Independent early-reflection gain, 0..1, default 0.35.
 */
earlyLevel: number, 
/**
 * Modulated allpass speed in Hz, 0..2, default 0.27.
 */
modulationRateHz: number, 
/**
 * Modulated allpass delay swing in milliseconds, 0..2, default 0.7.
 */
modulationDepthMs: number, 
/**
 * Wet stereo width, 0..1, default 1. Zero retains the wet mid signal.
 */
width: number, 
/**
 * Dry/wet balance, 0..1, default 0.3.
 */
mix: number, };
