// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatrixOperatorParams } from "./MatrixOperatorParams";

export type MatrixFmParams = { operators: [MatrixOperatorParams, MatrixOperatorParams, MatrixOperatorParams, MatrixOperatorParams, MatrixOperatorParams, MatrixOperatorParams], 
/**
 * `matrix[destination][source]`: signed radians per unit source output.
 * All routes, including the diagonal, use the previous sample.
 */
matrix: [[number, number, number, number, number, number], [number, number, number, number, number, number], [number, number, number, number, number, number], [number, number, number, number, number, number], [number, number, number, number, number, number], [number, number, number, number, number, number]], gain: number, };
