// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FmEnvelopeParams } from "./FmEnvelopeParams";

/**
 * Matrix operator, with independent carrier send and pitch-dependent level.
 */
export type MatrixOperatorParams = { ratio: number, level: number, envelope: FmEnvelopeParams, feedback: number, 
/**
 * Gain octaves per keyboard octave, centered on A4; bounded to 4x.
 */
keyScaling: number, output: number, };
