// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls for a tunable two-mode drum.
 */
export type MembraneParams = { 
/**
 * Fundamental at MIDI 60, Hz, 30..2000, default 160.
 */
pitchHz: number, 
/**
 * Time from strike to silence, ms, 10..4000, default 600.
 */
decayMs: number, 
/**
 * Second membrane mode and noise brightness, 0..1, default 0.5.
 */
tone: number, 
/**
 * Short noisy strike level, 0..1, default 0.2.
 */
snap: number, 
/**
 * Initial upward detuning, semitones, 0..24, default 7.
 */
pitchDropSemitones: number, 
/**
 * Pitch sweep time constant, ms, 1..500, default 65.
 */
pitchDecayMs: number, 
/**
 * Linear output gain, 0..1, default 0.8.
 */
level: number, };
