// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeterChangeId } from "./MeterChangeId";
import type { TimeSignature } from "./TimeSignature";

export type MeterChange = { 
/**
 * Monotonic document ID, shared with every other entity.
 */
id: MeterChangeId, tick: number, signature: TimeSignature, };
