// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable meter identity. Its JSON representation remains a numeric u32.
 */
export type MeterChangeId = number;
