// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { MidiHardwareSettings } from "./MidiHardwareSettings";
import type { MidiPort } from "./MidiPort";

export type MidiHardwareState = { settings: MidiHardwareSettings, inputs: Array<MidiPort>, outputs: Array<MidiPort>, inputConnected: boolean, outputConnected: boolean, 
/**
 * Runtime-only explicit audition destination, cleared on project replacement/removal.
 */
target: ChannelId | null, 
/**
 * Session document identity for guarded destination requests.
 */
generation: number, droppedEvents: number, error: string | null, };
