// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Append MIDI notes to the current project, optionally in shared bar sections.
 */
export type MidiImportOptions = { 
/**
 * Zero means one pattern per part, split only at the model limit.
 */
bars: number, sharePatterns: boolean, factoryDrums: boolean, tempo: boolean, timeSignature: boolean, channelMix: boolean, };
