// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternId } from "./PatternId";
import type { PlayMode } from "./PlayMode";

/**
 * A MIDI file contains notes and tempo, with no rendered audio or effects.
 */
export type MidiExportOptions = { mode: PlayMode, pattern: PatternId, 
/**
 * Format 0 instead of the default format 1.
 */
singleTrack: boolean, 
/**
 * 480 or 960 ticks per quarter note; other values are refused.
 */
ppq: number, runningStatus: boolean, swing: boolean, };
