// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MidiHardwareSettings = { 
/**
 * Opaque backend port IDs. None means disabled; never select a fallback.
 */
input: string | null, output: string | null, 
/**
 * None accepts all channels; otherwise 1..=16.
 */
inputChannel: number | null, 
/**
 * Live note forwarding only, on 1..=16. No song/clock output.
 */
outputChannel: number, };
