// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Review of a prepared import; the token refers to exactly the bytes reviewed.
 */
export type MidiImportPreview = { token: number, channels: Array<string>, patterns: number, clips: number, notes: number, length: number, adjustments: Array<string>, };
