import type { MixerRecording } from "./MixerRecording";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MixerTrackPatch = { dock?: import("./MixerDock").MixerDock, processing?: import("./TrackParams").TrackParams, name?: string, color?: number, volume?: number, pan?: number, muted?: boolean, solo?: boolean, recording?: MixerRecording, latencyOffsetMs?: number, };
