// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MixerTrackPatch = { name?: string, color?: number, volume?: number, pan?: number, muted?: boolean, solo?: boolean, };
