// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioInputRoute } from "./AudioInputRoute";
import type { MixerRecordMode } from "./MixerRecordMode";

export type MixerRecording = { input: AudioInputRoute | null, armed: boolean, monitor: boolean, monitorGain: number, monitorBufferMs: number, offsetMs: number, mode?: MixerRecordMode, };
