// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MixerDock } from "./MixerDock";
import type { MixerRecording } from "./MixerRecording";
import type { TrackParams } from "./TrackParams";

export type MixerTrackPatch = { dock?: MixerDock, processing?: TrackParams, latencyOffsetMs?: number, name?: string, color?: number, volume?: number, pan?: number, muted?: boolean, solo?: boolean, recording?: MixerRecording, };
