// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectSlot } from "./EffectSlot";
import type { ExternalOutputRoute } from "./ExternalOutputRoute";
import type { MixerDock } from "./MixerDock";
import type { MixerRecording } from "./MixerRecording";
import type { Send } from "./Send";
import type { TrackId } from "./TrackId";
import type { TrackParams } from "./TrackParams";

export type MixerTrack = { dock?: MixerDock, 
/**
 * Integrated post-slot EQ and stereo utilities, before the fader.
 */
processing?: TrackParams, 
/**
 * Utility-only strip fed by the current selection, with no audible routes.
 */
current?: boolean, id: TrackId, name: string, 
/**
 * Display color as 0xRRGGBB.
 */
color: number, 
/**
 * Fader as linear gain, 0 to [`MAX_GAIN`]. 1 is 0 dB.
 */
volume: number, 
/**
 * -1 is hard left, 1 is hard right.
 */
pan: number, muted: boolean, solo: boolean, 
/**
 * Where the track's output goes. `None` on the master, and on a track
 * that only feeds its sends. Routing never forms a cycle.
 */
output: TrackId | null, 
/**
 * Extra copies of the post-fader signal sent to other tracks.
 */
sends: Array<Send>, 
/**
 * Post-fader detector-only copies; they are never summed into the audible input.
 */
sidechains?: Array<Send>, 
/**
 * The track's effects, in the order the signal passes through them,
 * at most [`MAX_EFFECT_SLOTS`]. They come before the fader: what
 * arrives on the track runs through the effects, then the fader and
 * pan, and from there to the meter, the output and the sends. The
 * master has effects like any other track.
 */
effects: Array<EffectSlot>, recording?: MixerRecording, 
/**
 * Post-fader hardware destination on the currently selected output device.
 */
externalOutput?: ExternalOutputRoute, 
/**
 * Signed correction to the track's declared output latency, in milliseconds.
 * This compensates other routes; it does not add an audible delay here.
 */
latencyOffsetMs?: number, };
