// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MixerTrack } from "./MixerTrack";

export type Mixer = { 
/**
 * `tracks[0]` is always the master. At most [`MAX_MIXER_TRACKS`].
 */
tracks: Array<MixerTrack>, };
