// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectSlot } from "./EffectSlot";
import type { PluginBinding } from "./PluginBinding";
import type { TrackParams } from "./TrackParams";

export type MixerTrackPreset = { version: number, name: string, color: number, volume: number, pan: number, muted: boolean, processing: TrackParams, latencyOffsetMs: number, effects: Array<EffectSlot>, plugins: Array<PluginBinding>, };
