// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Send } from "./Send";
import type { TrackId } from "./TrackId";

export type MixerTrack = { id: TrackId, name: string, 
/**
 * Display color as 0xRRGGBB.
 */
color: number, 
/**
 * Fader as linear gain, 0 to [`MAX_GAIN`]. 1 is 0 dB.
 */
volume: number, 
/**
 * -1 is hard left, 1 is hard right.
 */
pan: number, muted: boolean, solo: boolean, 
/**
 * Where the track's output goes. `None` on the master, and on a track
 * that only feeds its sends. Routing never forms a cycle.
 */
output: TrackId | null, 
/**
 * Extra copies of the post-fader signal sent to other tracks.
 */
sends: Array<Send>, };
