// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackId } from "./TrackId";

/**
 * Stereo signed extrema, oldest first, from the track's post-fader meter tap.
 */
export type MixerWaveform = { track: TrackId, epoch: bigint, serial: bigint, sampleRate: number, bucketFrames: number, 
/**
 * [left min, left max, right min, right max], at most 64 buckets.
 */
points: Array<[number, number, number, number]>, };
