// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ADSR fields/defaults match synth::EnvelopeParams. Depth is filter octaves,
 * pitch cents, or normalized pan according to the enclosing field.
 */
export type ModulationEnvelope = { enabled: boolean, attackMs: number, decayMs: number, sustain: number, releaseMs: number, depth: number, };
