// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorphSnapshotParams } from "./MorphSnapshotParams";

export type MorphEqParams = { snapshotA: MorphSnapshotParams, snapshotB: MorphSnapshotParams, 
/**
 * 0 selects A, 1 selects B. Hz and Q interpolate logarithmically, dB linearly.
 */
morph: number, };
