// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MorphBandParams } from "./MorphBandParams";

export type MorphSnapshotParams = { 
/**
 * Four stored bell bands, with default centers 150, 600, 2500, 10000 Hz.
 */
bands: [MorphBandParams, MorphBandParams, MorphBandParams, MorphBandParams], };
