// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MorphBandParams = { 
/**
 * Center in Hz, 20 to 20,000; clamped below Nyquist during design.
 */
frequencyHz: number, 
/**
 * Bell gain in dB, -18 to 18; default zero.
 */
gainDb: number, 
/**
 * Band Q, 0.1 to 10; default 1.
 */
q: number, };
