// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel coding of an MP3 export. Mono averages the rendered stereo pair.
 */
export type Mp3Channels = "mono" | "stereo" | "jointStereo";
