// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MP3 rate policy. VBR quality runs from 0 (best) to 9 (smallest).
 */
export type Mp3Rate = { "mode": "cbr", bitrate: number, } | { "mode": "vbr", quality: number, };
