// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mp3Channels } from "./Mp3Channels";
import type { Mp3Rate } from "./Mp3Rate";

/**
 * MP3 settings. Absent settings mean 192 kbit/s joint stereo.
 */
export type Mp3Settings = { rate: Mp3Rate, channels: Mp3Channels, };
