// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandDynamicsParams } from "./BandDynamicsParams";

export type MultibandCompressorParams = { lowCrossoverHz: number, highCrossoverHz: number, low: BandDynamicsParams, mid: BandDynamicsParams, high: BandDynamicsParams, 
/**
 * Detector-only key with its own matching crossover. Missing key is silence.
 */
sidechain: boolean, };
