// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BandDynamicsParams } from "./BandDynamicsParams";

export type MultibandMaximizerParams = { lowCrossoverHz: number, highCrossoverHz: number, low: BandDynamicsParams, mid: BandDynamicsParams, high: BandDynamicsParams, sidechain: boolean, inputGainDb: number, ceilingDb: number, limiterReleaseMs: number, 
/**
 * Independent sample peak ceilings, after each band's compression.
 */
lowCeilingDb: number, midCeilingDb: number, highCeilingDb: number, };
