// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One-based bar/beat and a zero-based tick inside the beat.
 */
export type MusicalPosition = { bar: number, beat: number, tick: number, };
