// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";

export type Note = { id: NoteId, 
/**
 * Start in ticks from the beginning of the pattern. An edit can put a
 * note anywhere before [`MAX_PATTERN_TICKS`], the end of the longest
 * pattern.
 */
start: number, 
/**
 * Length in ticks, at least 1.
 */
length: number, 
/**
 * MIDI key, 0 to 127.
 */
key: number, 
/**
 * 0 to 1.
 */
velocity: number, 
/**
 * -1 is hard left, 1 is hard right. Added to the channel pan.
 */
pan: number, };
