// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EchoTime } from "./EchoTime";

export type NoteEchoSettings = { enabled: boolean, time: EchoTime, feedback: number, pitchSemitones: number, repeats: number, };
