// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteId } from "./NoteId";
import type { NotePatch } from "./NotePatch";

export type NoteUpdate = { id: NoteId, patch: NotePatch, };
