// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note length for a delay time that follows the tempo.
 */
export type NoteDivision = "whole" | "halfDotted" | "half" | "halfTriplet" | "quarterDotted" | "quarter" | "quarterTriplet" | "eighthDotted" | "eighth" | "eighthTriplet" | "sixteenthDotted" | "sixteenth" | "sixteenthTriplet" | "thirtySecond";
