// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note to add. Missing fields take the defaults a step would get.
 */
import type { NoteExpression } from "./NoteExpression";
export type NoteInit = { start: number, length: number, key: number, velocity?: number, pan?: number, expression?: NoteExpression, };
