// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCurveParameter } from "./NoteCurveParameter";
import type { NoteCurvePoint } from "./NoteCurvePoint";
import type { NoteId } from "./NoteId";

export type NoteExpressionCurve = { note: NoteId, parameter: NoteCurveParameter, points: Array<NoteCurvePoint>, };
