// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteEdge } from "./NoteEdge";
import type { NoteGroove } from "./NoteGroove";

export type NoteTransform = { "type": "legato" } | { "type": "staccato", factor: number, } | { "type": "chop", grid: number, } | { "type": "glue" } | { "type": "strum", spacing: number, velocityStep: number, descending: boolean, } | { "type": "flipTime" } | { "type": "flipPitch" } | { "type": "keyRange", low: number, high: number, transpose: number, octaves: boolean, } | { "type": "scaleVelocity", factor: number, } | { "type": "quantize", grid: number, strength: number, edge: NoteEdge, groove: NoteGroove, };
