// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteEnvelopeParams = { 
/**
 * Rising edge attacks, falling edge releases; hold true to sustain.
 */
trigger: boolean, attackMs: number, decayMs: number, sustain: number, releaseMs: number, depth: number, gain: number, };
