// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a note. Unique across the whole project.
 */
export type NoteId = number;
