// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeterChange } from "./MeterChange";
import type { NoteGridUnit } from "./NoteGridUnit";
import type { TimeSignature } from "./TimeSignature";

export type NoteMusicalGrid = { signature: TimeSignature, meters: Array<MeterChange>, unit: NoteGridUnit, divisor: number, };
