// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCurveParameter } from "./NoteCurveParameter";
import type { NoteCurvePoint } from "./NoteCurvePoint";

/**
 * Curve payload indexed to an input note, before native ids are allocated.
 */
export type NoteCurveInsert = { noteIndex: number, parameter: NoteCurveParameter, points: Array<NoteCurvePoint>, };
