// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteExpression } from "./NoteExpression";

export type NotePatch = { start?: number, length?: number, key?: number, velocity?: number, pan?: number, expression?: NoteExpression, };
