// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Original, repeating timing patterns. Offsets are fractions of the grid:
 * Swing delays odd divisions by 1/6, LatePairs by 1/4, and PushFour advances
 * every fourth division by 1/6. Straight has no offset.
 */
export type NoteGroove = "straight" | "swing" | "latePairs" | "pushFour";
