// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteArticulation } from "./NoteArticulation";

/**
 * Neutral values preserve legacy playback. Modulation X controls filter
 * cutoff and modulation Y controls resonance in the built-in voices.
 */
export type NoteExpression = { 
/**
 * Release amount, 0 to 1, default 0.5. Multiplies envelope release
 * duration by 1/8 to 8; its MIDI representation is release velocity.
 */
release: number, 
/**
 * Additional pitch in cents, -1200 to 1200, default 0.
 */
finePitchCents: number, 
/**
 * Per-voice cutoff offset, 0 to 1, default 0.5 (no offset).
 */
modulationX: number, 
/**
 * Per-voice resonance offset, 0 to 1, default 0.5 (no offset).
 */
modulationY: number, 
/**
 * Slide bends held voices without retriggering; portamento starts a
 * voice gliding from the most recent held pitch.
 */
articulation?: NoteArticulation, 
/**
 * Portamento duration in musical ticks. 1 to 245760, default 240.
 * A slide uses the slide note's own length instead.
 */
glideTicks?: number, 
/**
 * Optional note color group / zero-based MIDI channel, 0 through 15.
 * None keeps the channel's display color and automatic MIDI routing.
 */
colorGroup?: number, };
