// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Waveform } from "./Waveform";

/**
 * Settings of one oscillator of the [`SubtractiveSynth`].
 */
export type OscillatorParams = { 
/**
 * The waveform. Default saw.
 */
waveform: Waveform, 
/**
 * Volume, 0 to 1. An oscillator at 0 is off and costs nothing.
 * Default 0.
 */
level: number, 
/**
 * Tuning in semitones. -36 to 36, default 0.
 */
coarse: number, 
/**
 * Fine tuning in cents. -100 to 100, default 0.
 */
fineCents: number, 
/**
 * Share of each cycle the pulse waveform spends high. 0.5 is a square;
 * values toward either end sound thinner. 0.05 to 0.95, default 0.5.
 */
pulseWidth: number, 
/**
 * Position from left (-1) to right (1). Default 0.
 */
pan: number, };
