// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverdriveParams = { 
/**
 * Input drive in dB, 0..36; default 18.
 */
driveDb: number, 
/**
 * Unequal clip ceilings, 0..1; default 0.7.
 */
asymmetry: number, 
/**
 * Treble emphasis before clipping, 0..1; default 0.5.
 */
emphasis: number, 
/**
 * Post lowpass cutoff in Hz, 200..18000; default 6000.
 */
toneHz: number, 
/**
 * Output trim in dB, -24..12; default -6.
 */
outputDb: number, };
