// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamChoice } from "./ParamChoice";
import type { ParamKind } from "./ParamKind";
import type { ParamScale } from "./ParamScale";
import type { ParamUnit } from "./ParamUnit";

/**
 * Describes one control of a processor.
 */
export type ParamInfo = { 
/**
 * Where the value lives in the parameter struct's JSON, with dots
 * between levels: `"thresholdDb"`, `"lowShelf.gainDb"`,
 * `"oscillators.0.level"`.
 */
id: string, 
/**
 * The name to show.
 */
name: string, kind: ParamKind, unit: ParamUnit, scale: ParamScale, 
/**
 * Smallest value. For a toggle or a choice this is 0.
 */
min: number, 
/**
 * Largest value. For a toggle this is 1, and for a choice it is the
 * index of the last choice.
 */
max: number, default: number, 
/**
 * The options of a choice, in index order. Empty for the other kinds.
 */
choices: Array<ParamChoice>, };
