// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of control edits a parameter.
 */
export type ParamKind = "float" | "integer" | "toggle" | "choice";
