// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One option of a [`ParamKind::Choice`] parameter.
 */
export type ParamChoice = { 
/**
 * The value as it appears in the parameter struct's JSON.
 */
value: string, 
/**
 * The name to show.
 */
label: string, };
