// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unit a parameter's value is in, for labelling a control.
 */
export type ParamUnit = "none" | "decibels" | "hertz" | "milliseconds" | "seconds" | "fraction" | "semitones" | "cents" | "octaves" | "ratio" | "gain" | "pan";
