// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`PartialMorph`].
 */
export type PartialMorphParams = { 
/**
 * How many harmonics are sounded, counting the fundamental. 1 to 32,
 * default 24.
 */
partials: number, 
/**
 * Where between the two snapshots the sound sits. 0 is snapshot A, 1
 * is snapshot B, and every value between mixes their levels in that
 * proportion. Default 0.
 */
morph: number, 
/**
 * The levels of snapshot A, 0 to 1 each. The default is the
 * fundamental alone: a plain sine.
 */
snapshotA: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * The levels of snapshot B, 0 to 1 each. The default is the odd
 * harmonics of a saw, with the even ones silent: the hollow spectrum
 * of a square.
 */
snapshotB: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], voicing: VoicingParams, };
