// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The level of each of the [`MAX_PARTIALS`] partials.
 *
 * `serde` describes arrays of up to 32 entries, so a bank twice that wide
 * carries its own pair of impls. In JSON it is a plain array of numbers.
 * A shorter one leaves the partials past its end silent, so a project
 * written by a version with fewer partials, or a damaged one, still loads.
 */
export type PartialGains = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
