// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Lane } from "./Lane";
import type { NoteExpressionCurve } from "./NoteExpressionCurve";
import type { PatternId } from "./PatternId";
import type { TimeSignature } from "./TimeSignature";
import type { Timeline } from "./Timeline";

/**
 * A short musical idea: notes for any number of channels.
 *
 * The step sequencer and the piano roll edit the same notes. A step that is
 * on is a note at `step * TICKS_PER_STEP` with key [`DEFAULT_KEY`] and a
 * length of one step.
 */
export type Pattern = { noteCurves?: Array<NoteExpressionCurve>, id: PatternId, name: string, 
/**
 * Display color as 0xRRGGBB.
 */
color: number, 
/**
 * Length in sixteenth-note steps, 1 to 1024. The pattern loops at this
 * length, and notes that start at or after it do not play. They are
 * kept, so making the pattern longer again brings them back.
 */
lengthSteps: number, 
/**
 * None inherits the project's base meter. Tick-zero changes may override it.
 */
timeSignature?: TimeSignature, timeline?: Timeline, 
/**
 * Notes per channel, sorted by channel id. Channels with no notes have
 * no lane.
 */
lanes: Array<Lane>, };
