// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerformanceModel } from "./PerformanceModel";

export type PerformanceRackParams = { model: PerformanceModel, 
/**
 * Quarter-note beats in each captured slice, 0.125..=16; default 1.
 * Capped at 1 second to leave an equally sized recording region.
 */
loopBeats: number, 
/**
 * Treatment intensity, 0..=1; default 1. See the integration seam.
 */
amount: number, 
/**
 * Pitch Jump transposition, -24..=24 semitones; default 12.
 */
pitchSemitones: number, 
/**
 * Wet feedback written into the recording region, 0..=0.95; default 0.
 */
feedback: number, 
/**
 * Blend with the latency-aligned dry signal, 0..=1; default 1.
 */
mix: number, };
