// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceModel = "stutter" | "reverse" | "tapeStop" | "halfSpeed" | "doubleSpeed" | "beatRepeat" | "telephoneFilter" | "distortion" | "panSpin" | "fade" | "silenceGate" | "pitchJump";
