// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhaserParams = { 
/**
 * Sweep endpoints, each 20..=10000 Hz; defaults 200 and 2000. If
 * crossed, the smaller endpoint is used as the lower frequency.
 */
minHz: number, maxHz: number, 
/**
 * Log-frequency sweep rate, 0..=5 Hz; default 0.3. Zero freezes phase.
 */
rateHz: number, 
/**
 * Right LFO offset in cycles, 0..=1; default 0.25.
 */
stereoPhase: number, 
/**
 * Signed one-frame feedback, -0.85..=0.85; default 0.35.
 */
feedback: number, 
/**
 * Wet share, 0..=1; default 0.5 (deep notches without feedback).
 */
mix: number, };
