// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phoneme } from "./Phoneme";

/**
 * Inline phrase storage. Only the first `length` codes play; zero is empty.
 */
export type PhonemeBuffer = { codes: [Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme, Phoneme], length: number, };
