// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Synthetic articulations; these codes do not represent natural-language text.
 */
export type Phoneme = "silence" | "ah" | "ee" | "oo" | "eh" | "oh" | "noiseBurst" | "nasal";
