// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PitchScale } from "./PitchScale";

export type PitchCorrectParams = { 
/**
 * Pitch class, C=0..B=11.
 */
root: number, scale: PitchScale, 
/**
 * Time constant in ms, 0..500; zero snaps on each voiced estimate.
 */
speedMs: number, 
/**
 * Correction share, 0..1.
 */
amount: number, 
/**
 * A4 tuning, 400..480 Hz.
 */
tuningHz: number, mix: number, };
