// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PitchShiftParams = { 
/**
 * -24..24 semitones; ratio = 2^(semitones/12).
 */
semitones: number, mix: number, };
