// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistTrackId } from "./PlaylistTrackId";

export type PlaylistTrack = { id: PlaylistTrackId, name: string, muted: boolean, 
/**
 * Limits playlist playback to solo tracks; mute still wins.
 */
solo?: boolean, 
/**
 * 0 means uncolored; other values are 0xRRGGBB.
 */
color?: number, 
/**
 * Row height in CSS pixels; 0 follows the global row height.
 */
height?: number, };
