// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the transport plays. It is not part of a [`Project`]: the transport
 * has it, and a project file keeps it beside the project
 * ([`ProjectSession`](crate::file::ProjectSession)).
 */
export type PlayMode = "pattern" | "song";
