// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a playlist track (a lane of the song timeline).
 */
export type PlaylistTrackId = number;
