// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaylistTrackId } from "./PlaylistTrackId";

export type PlaylistTrack = { id: PlaylistTrackId, name: string, muted: boolean, };
