// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrangementBook } from "./ArrangementBook";
import type { AudioTakeGroup } from "./AudioTakeGroup";
import type { Clip } from "./Clip";
import type { PlaylistTrack } from "./PlaylistTrack";
import type { Timeline } from "./Timeline";

/**
 * The song timeline.
 */
export type Playlist = { 
/**
 * Saved arrangement references and grouping metadata.
 */
arrangementBook?: ArrangementBook, 
/**
 * Lanes of the timeline, in display order.
 */
tracks: Array<PlaylistTrack>, 
/**
 * Sorted by `start`, then `id`.
 */
clips: Array<Clip>, 
/**
 * Song meter changes and navigation markers. Absent in legacy v1 files.
 */
timeline?: Timeline, 
/**
 * Retained recording passes and the latest editable composite.
 */
takeGroups?: Array<AudioTakeGroup>, };
