// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls for [`super::Pluck`]. Decay is the nominal low-frequency RT60.
 */
export type PluckParams = { 
/**
 * Nominal decay, 0.1–12 seconds; default 2.
 */
decaySeconds: number, 
/**
 * Loop brightness, 0–1; default 0.65.
 */
brightness: number, 
/**
 * Excitation position along the string, 0.05–0.95; default 0.23.
 */
pickPosition: number, 
/**
 * Output gain, 0–1; default 0.8.
 */
level: number, };
