// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { EffectId } from "./EffectId";

/**
 * The project object a plugin replaces.
 */
export type PluginTarget = { "type": "instrument", channel: ChannelId, } | { "type": "effect", effect: EffectId, };
