// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A discovered auxiliary audio input in the native input list.
 */
export type PluginAuxInput = { index: number, name: string, channels: number, };
