// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginTarget } from "./PluginTarget";

export type PluginInstanceStatus = { target: PluginTarget, error: string, };
