// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A discovered parameter in native units. Its id survives list reordering.
 */
export type PluginParameter = { id: number, name: string, min: number, max: number, value: number, stepped: boolean, readOnly: boolean, automatable: boolean, };
