// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginEntry } from "./PluginEntry";
import type { PluginInstanceStatus } from "./PluginInstanceStatus";

export type PluginManagerState = { folders: Array<string>, entries: Array<PluginEntry>, blocked: Array<PluginEntry>, scanning: boolean, completed: number, total: number, current: string | null, error: string | null, instances: Array<PluginInstanceStatus>, };
