// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginEntry = { path: string, format: string, id: string, name: string, vendor: string, instrument: boolean, usable: boolean, error: string | null, };
