// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginAuxInput } from "./PluginAuxInput";
import type { PluginParameter } from "./PluginParameter";
import type { PluginTarget } from "./PluginTarget";

/**
 * Everything needed to reopen an instance. Missing files retain this data.
 */
export type PluginBinding = { target: PluginTarget, 
/**
 * "clap" or "vst3"; the model does not load either format.
 */
format: string, path: string, id: string, name: string, 
/**
 * Host-wrapped opaque state, including its version header.
 */
state: Array<number>, parameters: Array<PluginParameter>, 
/**
 * None selects the first auxiliary input. The index is in the native input list.
 */
sidechainInput?: number, auxiliaryInputs?: Array<PluginAuxInput>, };
