// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolarityParams = { 
/**
 * Multiply the left channel by -1; default false.
 */
left: boolean, 
/**
 * Multiply the right channel by -1; default false.
 */
right: boolean, };
