// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolyphonySettings = { maxVoices: number, monoLegato: boolean, portamentoMs: number, };
