// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Automation } from "./Automation";
import type { Channel } from "./Channel";
import type { HistoryView } from "./HistoryView";
import type { Mixer } from "./Mixer";
import type { Pattern } from "./Pattern";
import type { PatternId } from "./PatternId";
import type { Playlist } from "./Playlist";
import type { ProjectSettings } from "./ProjectSettings";
import type { SampleAsset } from "./SampleAsset";

/**
 * The changed sections of a project. A section that is absent did not
 * change. The UI keeps a copy of the project and merges patches into it.
 */
export type ProjectPatch = { 
/**
 * Counts up by one for every patch the document produces. A UI that
 * sees a gap has missed a patch and must fetch the whole project again.
 */
revision: number, settings?: ProjectSettings, samples?: Array<SampleAsset>, channels?: Array<Channel>, mixer?: Mixer, playlist?: Playlist, 
/**
 * Every automation of the project, in order.
 */
automations?: Array<Automation>, 
/**
 * Ids of every pattern, in order. Present when a pattern was added,
 * removed or reordered. Patterns missing from it were removed.
 */
patternOrder?: Array<PatternId>, 
/**
 * Full data of each pattern that was added or changed.
 */
patterns?: Array<Pattern>, history: HistoryView, 
/**
 * The project has edits that are not saved.
 */
dirty: boolean, };
