// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternId } from "./PatternId";
import type { PlayMode } from "./PlayMode";

/**
 * How a project was being played when it was saved, kept in its file so
 * that it opens the way it was left: a song opens in song mode.
 *
 * These are the transport's settings and not the project's. Changing one
 * is not an edit, cannot be undone and does not make the project unsaved;
 * whoever saves reads them off the transport, and whoever opens hands
 * them back to it.
 */
export type ProjectSession = { mode: PlayMode, 
/**
 * In song mode, whether the song starts over at its end.
 */
loopSong: boolean, 
/**
 * The pattern that plays in pattern mode. An id the project does not
 * have is for the reader to ignore.
 */
pattern?: PatternId, };
