// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeSignature } from "./TimeSignature";

export type ProjectSettings = { name: string, 
/**
 * Project author, at most 256 UTF-8 bytes after trimming.
 */
author?: string, 
/**
 * Project genre, at most 128 UTF-8 bytes after trimming.
 */
genre?: string, 
/**
 * Project comments, at most 16,384 UTF-8 bytes after trimming.
 */
comments?: string, 
/**
 * Tempo in beats per minute, [`MIN_TEMPO_BPM`] to [`MAX_TEMPO_BPM`].
 */
tempoBpm: number, timeSignature: TimeSignature, 
/**
 * Swing amount from 0 to 1. It delays every second sixteenth-note step.
 * At 1 that step lands two thirds of the way through its pair of steps,
 * which is a full triplet feel.
 */
swing: number, };
