// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Automation } from "./Automation";
import type { Channel } from "./Channel";
import type { Mixer } from "./Mixer";
import type { Pattern } from "./Pattern";
import type { Playlist } from "./Playlist";
import type { PluginBinding } from "./PluginBinding";
import type { ProjectSettings } from "./ProjectSettings";
import type { RetainedPluginState } from "./RetainedPluginState";
import type { SampleAsset } from "./SampleAsset";

/**
 * A whole project. Ids are allocated from `next_id` and never reused, so an
 * id means the same thing for the life of the project, across undo and redo.
 */
export type Project = { formatVersion: number, 
/**
 * The next id to hand out. Id 0 is reserved for the master mixer track.
 */
nextId: number, settings: ProjectSettings, samples: Array<SampleAsset>, 
/**
 * Channel rack, in display order.
 */
channels: Array<Channel>, 
/**
 * Patterns, in display order. A project always has at least one.
 */
patterns: Array<Pattern>, mixer: Mixer, playlist: Playlist, 
/**
 * The automation curves, in the order they were made. A curve plays
 * where a clip on the playlist puts it.
 */
automations: Array<Automation>, 
/**
 * Native plugin instances, saved even when their files are unavailable.
 */
plugins?: Array<PluginBinding>, 
/**
 * Opaque states from imported plugins, kept even before a compatible host exists.
 */
retainedPlugins?: Array<RetainedPluginState>, };
