// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the engine reports to the UI 60 times a second.
 */
export type RealtimeFrame = { playing: boolean, 
/**
 * Playhead in ticks. In pattern mode it is the position inside the
 * pattern; in song mode it is the position on the playlist.
 */
tick: number, 
/**
 * Peak levels since the last frame as linear gain, two per mixer track
 * in mixer order: left, right, left, right. The master comes first.
 */
meters: Array<number>, 
/**
 * Share of the audio buffer's time the engine spent computing it, 0 to
 * 1. Near 1 means dropouts are close.
 */
cpu: number, 
/**
 * Audio buffers that arrived late since the stream started.
 */
xruns: number, 
/**
 * Sampler voices sounding right now.
 */
voices: number, };
