// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomatedValue } from "./AutomatedValue";
import type { GainReduction } from "./GainReduction";
import type { MixerWaveform } from "./MixerWaveform";

/**
 * What the engine reports to the UI 60 times a second.
 */
export type RealtimeFrame = { 
/**
 * Existing analyzer's uncentered, normalized zero-lag stereo correlation,
 * finite and in -1..=1. Absent when no valid correlation is available.
 */
correlation?: number, 
/**
 * At most 64 ascending, uniformly grouped FFT bands from DC through
 * Nyquist. Each is summed mean-square power averaged across valid
 * stereo channels, not dB. Empty when no valid snapshot is available.
 */
spectrum?: Array<number>, 
/**
 * Short analyzer history, flattened row-major with the oldest valid row
 * first. At most 16 rows and 64 columns; each row follows `spectrum`'s
 * finite, nonnegative mean-square band contract. Invalid slices are
 * omitted. Empty (and omitted on the wire) when no slice is valid.
 * Columns match nonempty `spectrum`; the current engine uses 64 columns
 * even when the current spectrum is invalid and only older rows remain.
 */
spectrogram?: Array<number>, waveforms?: Array<MixerWaveform>, playing: boolean, 
/**
 * Playhead in ticks. In pattern mode it is the position inside the
 * pattern; in song mode it is the position on the playlist.
 */
tick: number, 
/**
 * Peak levels since the last frame as linear gain, two per mixer track
 * in mixer order: left, right, left, right. The master comes first.
 */
meters: Array<number>, 
/**
 * Share of the audio buffer's time the engine spent computing it, 0 to
 * 1. Near 1 means dropouts are close.
 */
cpu: number, 
/**
 * Audio buffers that arrived late since the stream started.
 */
xruns: number, 
/**
 * Voices sounding right now: the samplers' and the instruments'.
 * Audio clips are counted in `audio_clips`.
 */
voices: number, 
/**
 * Audio clips of the playlist playing right now, at most 128. A clip
 * that is fading out after a stop, a seek or an edit is not counted.
 */
audioClips: number, 
/**
 * Audio clips that should be sounding right now and are silent,
 * because 128 were playing already when each was to start. Such a
 * clip stays silent for its whole length. Zero while the song is not
 * playing. No more than 1,024 are counted.
 */
droppedClips: number, 
/**
 * How far each compressor and limiter of the project turned its
 * signal down since the last frame, in mixer order and, on one track,
 * in chain order. Effects of other kinds are not listed.
 */
gainReductions: Array<GainReduction>, 
/**
 * The automations that have their target in hand right now, in the
 * order of the project's automations, with the value each is giving
 * it. An automation is listed from the start of its first clip that
 * plays: while a clip of it plays, while its target holds the value
 * the last clip left, and after the song has stopped for as long as
 * it is still ringing out with the target held there. So this can
 * have entries while `playing` is false. Where several automations
 * move one target, the one whose clip decides is listed. Empty in
 * pattern mode, and once a stopped song has let go of its targets. At
 * most 128 are listed.
 *
 * A control whose target is listed here is being moved by the song:
 * show it at this value instead of the one stored in the project.
 */
automated: Array<AutomatedValue>, };
