// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomatedValue } from "./AutomatedValue";
import type { GainReduction } from "./GainReduction";

/**
 * What the engine reports to the UI 60 times a second.
 */
export type RealtimeFrame = { playing: boolean, 
/**
 * Playhead in ticks. In pattern mode it is the position inside the
 * pattern; in song mode it is the position on the playlist.
 */
tick: number, 
/**
 * Peak levels since the last frame as linear gain, two per mixer track
 * in mixer order: left, right, left, right. The master comes first.
 */
meters: Array<number>, 
/**
 * Share of the audio buffer's time the engine spent computing it, 0 to
 * 1. Near 1 means dropouts are close.
 */
cpu: number, 
/**
 * Audio buffers that arrived late since the stream started.
 */
xruns: number, 
/**
 * Voices sounding right now: the samplers' and the instruments'.
 */
voices: number, 
/**
 * How far each compressor and limiter of the project turned its
 * signal down since the last frame, in mixer order and, on one track,
 * in chain order. Effects of other kinds are not listed.
 */
gainReductions: Array<GainReduction>, 
/**
 * The automations that have their target in hand right now, in the
 * order of the project's automations, with the value each is giving
 * it. An automation is listed from the start of its first clip that
 * plays until the song stops: while a clip of it plays, and while its
 * target holds the value the last clip left. Where several
 * automations move one target, the one whose clip decides is listed.
 * Empty while the song is not playing, and in pattern mode. At most
 * 128 are listed.
 *
 * A control whose target is listed here is being moved by the song:
 * show it at this value instead of the one stored in the project.
 */
automated: Array<AutomatedValue>, };
