// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingAlignmentStatus } from "./RecordingAlignmentStatus";
import type { RecordingMonitorStatus } from "./RecordingMonitorStatus";
import type { RecordingTakeInfo } from "./RecordingTakeInfo";
import type { RecordingTrackInfo } from "./RecordingTrackInfo";

export type RecordingState = { active: boolean, frames: number, sampleRate: number, startTick: number, error: string | null, alignment?: RecordingAlignmentStatus, takes?: Array<RecordingTakeInfo>, monitor?: RecordingMonitorStatus, tracks?: Array<RecordingTrackInfo>, };
