// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An input's channel count and common rates, without opening capture.
 */
export type RecordingInput = { host: string, device: string, channels: number, sampleRates: Array<number>, };
