// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackId } from "./TrackId";

export type RecordingMonitorSettings = { track: TrackId, gain: number, bufferMs: number, };
