// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MixerRecordMode } from "./MixerRecordMode";
import type { TrackId } from "./TrackId";

export type RecordingMixerTap = { track: TrackId, mode: MixerRecordMode, };
