// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingTakeSelection = { "type": "all" } | { "type": "latest" } | { "type": "only", indices: Array<number>, } | { "type": "except", indices: Array<number>, };
