// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingState = { active: boolean, frames: number, sampleRate: number, startTick: number, error: string | null, };
