import type { RecordingMixerTap } from "./RecordingMixerTap";
import type { RecordingMonitorSettings } from "./RecordingMonitorSettings";
import type { RecordingLoopOptions } from "./RecordingLoopOptions";
import type { RecordingAlignment } from "./RecordingAlignment";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zero-based hardware channels. Missing right duplicates left into stereo.
 */
export type RecordingSource = { host: string, device: string, left: number, right: number | null, alignment?: RecordingAlignment, loopRecording?: RecordingLoopOptions, monitor?: RecordingMonitorSettings, armedTracks?: boolean, mixerTap?: RecordingMixerTap, };
