// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zero-based hardware channels. Missing right duplicates left into stereo.
 */
export type RecordingSource = { host: string, device: string, left: number, right: number | null, };
