// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Positive offsets advance the take relative to the playback clock.
 */
export type RecordingAlignment = { synchronize: boolean, driftCorrection: boolean, offsetMs: number, inputSampleRate: number | null, };
