// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TickRange } from "./TickRange";

export type RecordingLoopOptions = { region: TickRange, };
