// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";

/**
 * One thing a report says.
 */
export type ReportLine = { outcome: Outcome, 
/**
 * How many times this came up.
 */
count: number, text: string, };
