// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportLine } from "./ReportLine";
import type { ReportSection } from "./ReportSection";

/**
 * One category of a report.
 */
export type ReportCategory = { section: ReportSection, title: string, 
/**
 * Things that came across as they were.
 */
exact: number, approximated: number, placeholders: number, dropped: number, 
/**
 * What there is to say, in the order it came up. Lines with the same
 * words are one line with a count.
 */
lines: Array<ReportLine>, 
/**
 * Lines left out because the category already had
 * [`MAX_LINES_PER_CATEGORY`].
 */
moreLines: number, };
