// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The parts of a project a report is divided into, in the order a report
 * lists them.
 */
export type ReportSection = "project" | "channels" | "samples" | "patterns" | "notes" | "mixer" | "effects" | "playlist" | "automation" | "other";
