// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TablePartial } from "./TablePartial";
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`Resynth`].
 */
export type ResynthParams = { 
/**
 * How many rows of the table are played, from the top. 1 to 32,
 * default 16.
 */
partials: number, 
/**
 * Multiplies every ratio in the table, which moves the partials apart
 * or together without touching their levels. 0.5 to 2, default 1.
 */
stretch: number, 
/**
 * The table: a frequency ratio, a level and a starting phase per
 * partial. The default is the harmonic series with the levels of a
 * saw.
 */
table: [TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial, TablePartial], voicing: VoicingParams, };
