// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { TrackId } from "./TrackId";

/**
 * A plugin state the importer understands only as opaque bytes. Source ids
 * remain descriptive metadata after a channel or track is removed.
 */
export type RetainedPluginState = { source: string, internalName: string, name?: string, vendor?: string, format?: string, path?: string, channel?: ChannelId, track?: TrackId, slot?: number, 
/**
 * The original wrapper/state; it is not executable code.
 */
state: Array<number>, };
