// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings of the [`Reverb`].
 */
export type ReverbParams = { 
/**
 * Size of the space, from a small room (0) to a large hall (1).
 * Default 0.5. It sets how far apart the echoes are, not how long they
 * last.
 */
size: number, 
/**
 * Time for the tail to fade by 60 dB (RT60), in seconds. 0.1 to 20,
 * default 1.8.
 */
decayS: number, 
/**
 * Gap between the dry sound and the start of the reverb, in ms. 0 to
 * 250, default 10.
 */
preDelayMs: number, 
/**
 * How much faster the treble fades than the rest. At 0 all
 * frequencies last the same; at 1 the top of the spectrum lasts a
 * tenth as long. 0 to 1, default 0.5.
 */
damping: number, 
/**
 * How smeared the echoes are from the start. Low values let single
 * echoes through at the beginning; high values give a smooth wash. 0
 * to 1, default 0.8.
 */
diffusion: number, 
/**
 * Level of the first distinct reflections, which tell the ear how
 * close the walls are. 0 to 1, default 0.5.
 */
earlyLevel: number, 
/**
 * How much the tail slowly shimmers in pitch, which keeps it from
 * ringing. 0 to 1, default 0.25.
 */
modulation: number, 
/**
 * Removes lows from what enters the reverb, in Hz. 20 to 1000,
 * default 100.
 */
lowCutHz: number, 
/**
 * Removes highs from what enters the reverb, in Hz. 1000 to 20000,
 * default 10000.
 */
highCutHz: number, 
/**
 * Stereo width of the reverb, from mono (0) to full (1). Default 1.
 */
width: number, 
/**
 * Balance between the dry input (0) and the reverb (1). Default 0.3.
 * Use 1 on a send track.
 */
mix: number, };
