// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FmEnvelopeParams } from "./FmEnvelopeParams";
import type { HybridOscillatorParams } from "./HybridOscillatorParams";

export type RingHybridParams = { oscillators: [HybridOscillatorParams, HybridOscillatorParams, HybridOscillatorParams], 
/**
 * Oscillator 2 -> 1 phase modulation, in radians.
 */
fm21: number, 
/**
 * Oscillator 3 -> 1 phase modulation, in radians.
 */
fm31: number, 
/**
 * Oscillator 3 -> 2 phase modulation, in radians.
 */
fm32: number, 
/**
 * Crossfade oscillator 1 into its product with oscillator 2.
 */
ring12: number, 
/**
 * Crossfade that result into its product with oscillator 3.
 */
ring13: number, cutoffHz: number, resonance: number, ampEnvelope: FmEnvelopeParams, gain: number, };
