// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomParams = { size: number, 
/**
 * Nominal low-frequency RT60, 0.1..1.5 seconds; default 0.45.
 */
decayS: number, preDelayMs: number, damping: number, earlyLevel: number, width: number, mix: number, };
