// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Facts about an audio file, with a waveform overview for drawing.
 */
export type SampleInfo = { path: string, name: string, sampleRate: number, channels: number, frames: number, durationSecs: number, 
/**
 * Waveform overview as minimum and maximum pairs, one pair per bucket
 * across the file, all channels mixed: min, max, min, max.
 */
peaks: Array<number>, };
