// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mono source audio. Only `data[..len]` plays; empty tables are silent.
 * `sample_rate` is the source rate, independently of the output rate.
 */
export type SampleTable = { data: number[], len: number, sampleRate: number, };
