// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SamplerPatch = { rootKey?: number, tune?: number, gain?: number, start?: number, end?: number, reverse?: boolean, cutSelf?: boolean, cutGroup?: number, };
