// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipStretchQuality } from "./ClipStretchQuality";
import type { SamplerKeyRange } from "./SamplerKeyRange";

/**
 * Musical settings only; rendered banks are never serialized.
 */
export type SamplerStretch = { "mode": "tape" } | { "mode": "spectral", ratio: number, quality: ClipStretchQuality, formants: boolean, range: SamplerKeyRange, };
