// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Envelope } from "./Envelope";
import type { SampleId } from "./SampleId";
import type { SamplerLoopMode } from "./SamplerLoopMode";
import type { SamplerStretch } from "./SamplerStretch";

export type SamplerSettings = { sample: SampleId | null, 
/**
 * Independent duration/pitch is prepared for an explicit inclusive MIDI range.
 */
stretch?: SamplerStretch, 
/**
 * The key that plays the sample at its recorded pitch.
 */
rootKey: number, 
/**
 * Tuning offset in semitones, -48 to 48. Fractions are fine tuning.
 */
tune: number, 
/**
 * Extra linear gain applied to the sample, 0 to [`MAX_GAIN`].
 */
gain: number, 
/**
 * Playback start as a fraction of the sample, 0 to 1.
 */
start: number, 
/**
 * Playback end as a fraction of the sample, 0 to 1, greater than `start`.
 */
end: number, reverse: boolean, loopMode?: SamplerLoopMode, 
/**
 * Loop start as a fraction of the trimmed region, in source order.
 */
loopStart?: number, 
/**
 * Exclusive loop end as a fraction of the trimmed region.
 */
loopEnd?: number, 
/**
 * With no envelope a one-shot ignores note length, which drum hits want.
 * Loops use a short release when this is absent; an envelope gates either.
 */
envelope: Envelope | null, 
/**
 * A new note on this channel stops the notes already playing on it.
 */
cutSelf: boolean, 
/**
 * Channels that share a nonzero cut group stop each other, such as an
 * open and a closed hi-hat. 0 means no group.
 */
cutGroup: number, };
