// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a sample's audio file lives.
 */
export type SamplePath = { "kind": "factory", "path": string } | { "kind": "project", "path": string } | { "kind": "external", "path": string };
