// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SamplerLoopMode } from "./SamplerLoopMode";
import type { SamplerStretch } from "./SamplerStretch";

export type SamplerPatch = { stretch?: SamplerStretch, rootKey?: number, tune?: number, gain?: number, start?: number, end?: number, reverse?: boolean, loopMode?: SamplerLoopMode, loopStart?: number, loopEnd?: number, cutSelf?: boolean, cutGroup?: number, };
