// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loop repeats while a note is held and during its envelope release.
 */
export type SamplerLoopMode = "off" | "forward" | "pingPong";
