// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Worker progress is session state, never project musical data.
 */
export type SamplerPreparationProgress = { request: number, completed: number, total: number, current: boolean, };
