// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`ScanSynth`].
 */
export type ScanSynthParams = { 
/**
 * The row that is scanned: 32 values from -1 to 1, which are the
 * waveform. One cycle of the note covers all of them, lowest index
 * first. The default is a ramp.
 */
row: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * Whether the steps are joined by a straight line instead of being
 * held. Default off, which is the staircase the instrument is for.
 */
interpolate: boolean, 
/**
 * Rounds off the corners of the staircase. 0 leaves them alone;
 * toward 1 the steps are smeared into one another and the sound
 * darkens. 0 to 1, default 0.
 */
smoothing: number, voicing: VoicingParams, };
