// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScratchParams = { 
/**
 * 0 is oldest, 1 newest, within the recent loop. Default 1.
 */
position: number, 
/**
 * Freeze the recording so position addresses a stable record. Default false.
 */
freeze: boolean, 
/**
 * Quarter-note beats in the record, 0.125..=16; default 4, capped at 2 s.
 */
loopBeats: number, 
/**
 * Dry/wet blend, 0..=1; default 1.
 */
mix: number, };
