// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoicingParams } from "./VoicingParams";

/**
 * Settings of the [`SeedPatch`].
 */
export type SeedPatchParams = { 
/**
 * The number the whole spectrum is derived from. Any two seeds give
 * unrelated timbres, and the same seed always gives the same one. 0 to
 * 16777215, default 12345.
 */
seed: number, 
/**
 * How many partials are sounded, counting the lowest. 1 to 64,
 * default 32. Raising it adds partials above the ones already there
 * rather than changing them.
 */
partials: number, 
/**
 * How far the seed is allowed to move the partials off the harmonic
 * series. At 0 the spectrum is harmonic and only the levels are drawn;
 * toward 1 the partials wander and the sound turns metallic. 0 to 1,
 * default 0.3.
 */
spread: number, 
/**
 * How much quieter each partial is than the one below. 0 to 1,
 * default 0.3.
 */
rolloff: number, voicing: VoicingParams, };
