// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The order is the stable automation/descriptor order, independent of Rust
 * enum discriminants. Gain affects only the last three modes.
 */
export type SelectableFilterMode = "lowpass" | "highpass" | "bandpass" | "notch" | "lowShelf" | "peak" | "highShelf";
