// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectableFilterMode } from "./SelectableFilterMode";

export type SelectableFilterParams = { 
/**
 * Response type; default lowpass.
 */
mode: SelectableFilterMode, 
/**
 * Cutoff, center or shelf midpoint, Hz, 20..=20000; default 1000.
 */
frequencyHz: number, 
/**
 * Q, 0.5..=10; default 1/sqrt(2). Bandpass peak is unity at every Q.
 */
q: number, 
/**
 * Shelf/peak gain in dB, -18..=18; default 0. Ignored by cut/notch modes.
 */
gainDb: number, };
