// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendTapParams = { 
/**
 * Tap gain, 0 to 1; default 0 (silent).
 */
level: number, };
