// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeSignature } from "./TimeSignature";

export type SettingsPatch = { name?: string, author?: string, genre?: string, comments?: string, tempoBpm?: number, timeSignature?: TimeSignature, swing?: number, };
