// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SevenBandParams = { 
/**
 * Gains in dB, -18 to 18, ordered by ascending band frequency; default zero.
 */
gainsDb: [number, number, number, number, number, number, number], };
