// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slice Deck's additional controls. Pitch is semitones, gain is linear.
 */
export type SliceSettings = { pitch: number, gain: number, reverse: boolean, };
