// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleTable } from "./SampleTable";
import type { SliceSettings } from "./SliceSettings";

/**
 * Slice Deck parameters. Table frames are source data, not automatable controls.
 */
export type SliceDeckParams = { table: SampleTable, baseKey: number, level: number, releaseMs: number, 
/**
 * Ordered normalized slice starts. Each end is the next start, or 1.
 */
sliceStarts: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], slices: [SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings, SliceSettings], };
