// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SoftClipperParams = { 
/**
 * Peak ceiling in dBFS, -24 to 0; default 0.
 */
ceilingDb: number, 
/**
 * Fraction of the ceiling occupied by the rounded knee, 0.05 to 1; default 0.5.
 */
knee: number, };
