// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhonemeBuffer } from "./PhonemeBuffer";

/**
 * Controls for Speech Voice. All storage is fixed and can be copied to audio.
 */
export type SpeechVoiceParams = { phrase: PhonemeBuffer, 
/**
 * Phonemes per second, 0.5–30; default 6.
 */
rate: number, 
/**
 * Transposition relative to the note key, -24–24 semitones; default 0.
 */
pitch: number, 
/**
 * Release duration, 5–2000 milliseconds; default 80.
 */
releaseMs: number, 
/**
 * Output gain, 0–1; default 0.8.
 */
level: number, };
