// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Haas decorrelation is injected as opposite side signals, so summing the
 * outputs retains the original mid exactly, including during automation.
 */
export type SpreaderParams = { width: number, haasMs: number, amount: number, mix: number, };
