// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StackedFlangerParams = { delayMs: number, depthMs: number, rate1Hz: number, rate2Hz: number, feedback: number, toneHz: number, spread: number, mix: number, };
