// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings for Windfall's [`StageStack`].
 */
export type StageStackParams = { 
/**
 * Saturator input gain in dB, 0 to 36; default 0.
 */
driveDb: number, 
/**
 * Harmonic color, 0 (odd only) to 1 (added even harmonics); default 0.
 */
tone: number, 
/**
 * Wet sample ceiling in dBFS, -24 to 0; default 0.
 */
ceilingDb: number, 
/**
 * Dry/wet blend, 0 to 1; default 1. Dry audio bypasses the ceiling.
 */
mix: number, };
