// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frequency-selective side processing: a two-pole highpass removes bass from
 * S, while M is preserved. Matrix coefficients alone cannot do this.
 */
export type StereoEnhancerParams = { width: number, bassHz: number, bassLock: number, balance: number, mix: number, };
