// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatrixMode } from "./MatrixMode";

export type StereoMatrixParams = { 
/**
 * Coordinate/routing view; default stereo. Every view uses the same matrix.
 */
mode: MatrixMode, 
/**
 * First input to first output, -2 to 2; default 1.
 */
ll: number, 
/**
 * Second input to first output, -2 to 2; default 0.
 */
lr: number, 
/**
 * First input to second output, -2 to 2; default 0.
 */
rl: number, 
/**
 * Second input to second output, -2 to 2; default 1.
 */
rr: number, 
/**
 * Left output delay, 0 to 50 ms; rounded to samples, default 0.
 */
leftDelayMs: number, 
/**
 * Right output delay, 0 to 50 ms; rounded to samples, default 0.
 */
rightDelayMs: number, };
