// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeParams } from "./EnvelopeParams";
import type { FilterParams } from "./FilterParams";
import type { LfoParams } from "./LfoParams";
import type { OscillatorParams } from "./OscillatorParams";
import type { VoiceMode } from "./VoiceMode";

/**
 * Settings of the [`SubtractiveSynth`].
 */
export type SynthParams = { 
/**
 * The three oscillators. By default the first is a saw at full level
 * and the other two are off.
 */
oscillators: [OscillatorParams, OscillatorParams, OscillatorParams], 
/**
 * Copies of each oscillator stacked per note. 1 to 7, default 1.
 */
unisonVoices: number, 
/**
 * How far apart the outermost copies are tuned, in cents each way. 0
 * to 100, default 20.
 */
unisonDetuneCents: number, 
/**
 * How far the copies are spread across the stereo field, 0 to 1.
 * Default 0.7.
 */
unisonSpread: number, filter: FilterParams, 
/**
 * Shapes the volume of each note. Default: attack 2 ms, decay 200 ms,
 * sustain 0.8, release 150 ms.
 */
ampEnvelope: EnvelopeParams, 
/**
 * Moves the filter cutoff over each note by
 * `filter.envelope_octaves`. Default: attack 2 ms, decay 300 ms,
 * sustain 0.3, release 200 ms.
 */
filterEnvelope: EnvelopeParams, lfos: [LfoParams, LfoParams], 
/**
 * Default poly.
 */
voiceMode: VoiceMode, 
/**
 * Time the pitch takes to slide from the previous note, in ms. 0 to
 * 2000, default 0 (no slide).
 */
glideMs: number, 
/**
 * Most notes sounding at once in poly mode. One more takes over the
 * oldest. 1 to 32, default 16.
 */
polyphony: number, 
/**
 * How much playing softly lowers the volume. At 0 every note is at
 * full level; at 1 volume follows velocity directly. Default 0.7.
 */
ampVelocity: number, 
/**
 * Output level as a linear gain. 0 to 2, default 0.25, which leaves
 * room for chords.
 */
gain: number, 
/**
 * Output position from left (-1) to right (1). Default 0.
 */
pan: number, };
