// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the [`Resynth`] table: a partial of the sound it plays.
 */
export type TablePartial = { 
/**
 * The partial's frequency as a multiple of the note's pitch. 0.25 to
 * 64. Nothing requires it to be a whole number.
 */
ratio: number, 
/**
 * The partial's level, 0 to 1.
 */
gain: number, 
/**
 * Where in its cycle the partial starts, 0 to 1. Every note starts its
 * partials here, so the same note always sounds the same.
 */
phase: number, };
