// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Half-open absolute song ticks, checked before transport/export mutation.
 */
export type TickRange = { start: number, end: number, };
