// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TickRange } from "./TickRange";

/**
 * Session-only timeline playback state; no musical edit or undo entry.
 */
export type TimelinePlaybackState = { 
/**
 * Transient, exact JS-safe monotonic publication number. Never wraps.
 */
request: number, generation: number, revision: number, region: TickRange | null, navigationOverflows: number, };
