// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeterChange } from "./MeterChange";
import type { TimelineMarker } from "./TimelineMarker";

/**
 * Optional persisted song musical data. Selection/regions are session data.
 */
export type Timeline = { meters: Array<MeterChange>, 
/**
 * Sorted by tick then ID. Named labels may share a position.
 */
markers: Array<TimelineMarker>, };
