// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkerKind } from "./MarkerKind";
import type { TimelineMarkerId } from "./TimelineMarkerId";

export type TimelineMarker = { id: TimelineMarkerId, tick: number, name: string, kind: MarkerKind, };
