// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable marker identity, distinct from meter and other document identities.
 */
export type TimelineMarkerId = number;
