// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeSignature = { 
/**
 * Beats per bar, 1 to 16.
 */
numerator: number, 
/**
 * Beat unit: 2, 4, 8 or 16.
 */
denominator: number, };
