// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportMode } from "./TransportMode";

export type TimeTransportParams = { 
/**
 * False records/passes live audio; a rising edge captures preceding audio.
 */
trigger: boolean, mode: TransportMode, 
/**
 * Capture length in quarter-note beats, 0.125..=16; default 1, capped at 2 s.
 */
loopBeats: number, 
/**
 * Slice playback rate, 0.25..=4; default 1 (ignored in Hold).
 */
rate: number, 
/**
 * Dry/wet blend, 0..=1; default 1.
 */
mix: number, };
