// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBand } from "./EqBand";

export type TrackParams = { eqEnabled: boolean, low: EqBand, mid: EqBand, high: EqBand, invertLeft: boolean, invertRight: boolean, swap: boolean, 
/**
 * -1 doubles side, 0 preserves stereo, +1 sums to mono.
 */
separation: number, };
