// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a mixer track. The master is always [`TrackId::MASTER`].
 */
export type TrackId = number;
