// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelId } from "./ChannelId";
import type { SampleId } from "./SampleId";

export type TrackKind = { "type": "instrument", channel: ChannelId, } | { "type": "audio", source: SampleId, };
