// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternId } from "./PatternId";
import type { PlayMode } from "./PlayMode";
import type { MetronomeSettings } from "./MetronomeSettings";

export type TransportState = { playing: boolean, mode: PlayMode, 
/**
 * The pattern that plays in pattern mode.
 */
pattern: PatternId, 
/**
 * In song mode, jump back to the start at the end of the last clip.
 */
loopSong: boolean, metronome?: MetronomeSettings | null, countInBars?: number | null, countInRemaining?: number | null, };
