// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternId } from "./PatternId";
import type { PlayMode } from "./PlayMode";
import type { MetronomeSettings } from "./MetronomeSettings";

/**
 * A change to the transport. `None` leaves a field alone.
 */
export type TransportPatch = { mode?: PlayMode, pattern?: PatternId, loopSong?: boolean, metronome?: MetronomeSettings, countInBars?: number, };
