// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalogEnvelopeParams } from "./AnalogEnvelopeParams";
import type { AnalogOscParams } from "./AnalogOscParams";

export type TripleOscParams = { oscillators: [AnalogOscParams, AnalogOscParams, AnalogOscParams], cutoffHz: number, resonance: number, envelopeAmount: number, envelope: AnalogEnvelopeParams, gain: number, };
