// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TunerParams = { 
/**
 * Frequency of MIDI note 69 in Hz, 400 to 480; default 440.
 */
referenceHz: number, };
