// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VintageChorusParams = { delayMs: number, depthMs: number, rateHz: number, spread: number, toneHz: number, mix: number, };
