// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VintagePhaserParams = { minHz: number, maxHz: number, rateHz: number, feedback: number, colorHz: number, stereoPhase: number, mix: number, };
