// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocoderParams = { 
/**
 * 16 = classic resolution, 32 = detailed resolution. Intermediate counts
 * rebuild a real bank with that many filters, not a preset label.
 */
bandCount: number, 
/**
 * Envelope-to-carrier band offset, -1..1 maps to +/-4 bands.
 */
color: number, attackMs: number, releaseMs: number, gain: number, mix: number, };
