// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvelopeParams } from "./EnvelopeParams";

/**
 * The controls every additive instrument shares.
 */
export type VoicingParams = { 
/**
 * Shapes the volume of each note. Default: attack 5 ms, decay 400 ms,
 * sustain 0.7, release 300 ms.
 */
envelope: EnvelopeParams, 
/**
 * Most notes sounding at once. One more takes over the oldest. 1 to
 * 16, default 8. An additive voice costs one sine per partial per
 * sample, so this is the control that decides what the instrument
 * costs.
 */
polyphony: number, 
/**
 * How much playing softly lowers the volume. At 0 every note is at
 * full level; at 1 volume follows velocity directly. Default 0.7.
 */
velocity: number, 
/**
 * Output level as a linear gain. 0 to 2, default 0.2. Partial levels
 * add up, so this is where the room for a chord is made.
 */
gain: number, 
/**
 * Output position from left (-1) to right (1). Default 0.
 */
pan: number, };
