// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeGateParams = { 
/**
 * Sixteen linear gains, 0..=1; default unity. These are the volume curve.
 */
steps: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], 
/**
 * Quarter-note beats per cycle, 0.125..=16; default 4. Capped at 2 seconds.
 */
loopBeats: number, 
/**
 * Probability per step boundary of replaying preceding audio, 0..=1.
 */
retriggerChance: number, 
/**
 * Number of preceding steps to jump back, 1..=16; default 1.
 */
retriggerSteps: number, 
/**
 * Recirculated wet signal, 0..=0.95; default 0.
 */
feedback: number, 
/**
 * Dry/wet blend, 0..=1; default 1.
 */
mix: number, };
