// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WaveshaperParams = { 
/**
 * Input gain in dB, -24..36; default 0.
 */
inputDb: number, 
/**
 * Output trim in dB, -24..12; default 0.
 */
outputDb: number, 
/**
 * Output at each fixed input knot; values are bounded to -1..=1.
 */
curve: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
