// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleTable } from "./SampleTable";

/**
 * Wave Ride parameters. Table frames are source data, not automatable controls.
 */
export type WaveRideParams = { table: SampleTable, rootKey: number, durationMs: number, pitch: number, level: number, releaseMs: number, 
/**
 * Eight normalized source positions at equally spaced envelope times.
 */
positions: [number, number, number, number, number, number, number, number], };
