// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The waveform an oscillator plays.
 */
export type Waveform = "sine" | "triangle" | "saw" | "square" | "pulse" | "whiteNoise" | "pinkNoise";
