// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalogEnvelopeParams } from "./AnalogEnvelopeParams";

export type WaveLaneParams = { scan: number, cutoffHz: number, resonance: number, envelopeAmount: number, envelope: AnalogEnvelopeParams, gain: number, };
