//! The event ids the sources have a name for.
//!
//! An id with a name here is known, whether or not this crate reads it. An
//! id without one is new: none of the sources has seen it, and a file full
//! of them was saved by a version of FL Studio none of them knows.
//!
//! The names are this crate's own words for what PyFLP, DawVert, LMMS and
//! FLParser call the events.

/// What an event id is, in a few words. `None` for an id none of the
/// sources names.
pub fn event_name(id: u8) -> Option<&'static str> {
    Some(match id {
        0 => "channel enabled",
        1 => "note on (legacy)",
        2 => "channel volume (legacy)",
        3 => "channel pan (legacy)",
        4 => "MIDI channel (legacy)",
        5 => "MIDI note (legacy)",
        6 => "MIDI patch (legacy)",
        7 => "MIDI bank (legacy)",
        9 => "loop active",
        10 => "show info",
        11 => "swing",
        12 => "main volume (legacy)",
        13 => "stretch (legacy)",
        14 => "pitchable (legacy)",
        15 => "channel zipped",
        16 => "delay flags (legacy)",
        17 => "time signature numerator",
        18 => "time signature denominator",
        19 => "use loop points (legacy)",
        20 => "loop type",
        21 => "channel type",
        22 => "channel target insert",
        23 => "pan law",
        26 => "pattern looped",
        27 => "insert flags (legacy)",
        28 => "licensed",
        29 => "plugin delay compensation",
        30 => "play truncated notes",
        32 => "channel locked",
        33 => "marker numerator",
        34 => "marker denominator",
        64 => "new channel",
        65 => "new pattern",
        66 => "tempo (legacy)",
        67 => "current pattern",
        68 => "pattern data (legacy)",
        69 => "frequency tilt",
        70 => "sampler effect flags",
        71 => "cutoff",
        72 => "step volume (legacy)",
        73 => "step pan (legacy)",
        74 => "preamp",
        75 => "fade out",
        76 => "fade in",
        77 => "step note (legacy)",
        78 => "step pitch (legacy)",
        79 => "step mix (legacy)",
        80 => "main pitch",
        81 => "random channel (legacy)",
        82 => "mix channel (legacy)",
        83 => "resonance",
        84 => "loop bar (legacy)",
        85 => "stereo delay",
        86 => "pogo",
        87 => "step resonance (legacy)",
        88 => "step cutoff (legacy)",
        89 => "time shift",
        90 => "loop end bar (legacy)",
        91 => "step (legacy)",
        92 => "step shift (legacy)",
        93 => "tempo fraction (legacy)",
        94 => "layer child",
        95 => "insert icon",
        97 => "channel swing",
        98 => "effect slot number",
        99 => "new arrangement",
        100 => "current arrangement",
        128 => "color",
        129 => "playlist item (legacy)",
        130 => "echo (legacy)",
        131 => "ring modulation",
        132 => "cut groups",
        133 => "channel rack height",
        135 => "root note",
        136 => "reserved",
        137 => "main resonance and cutoff (legacy)",
        138 => "delay mod",
        139 => "sampler reverb",
        140 => "stretch time",
        141 => "note (legacy)",
        142 => "fine tune",
        143 => "sampler flags",
        144 => "layer flags",
        145 => "channel group",
        146 => "current channel group",
        147 => "insert output",
        148 => "time marker",
        149 => "insert color",
        150 => "pattern color",
        152 => "playlist loop",
        153 => "sample rate (AU)",
        154 => "insert input",
        155 => "icon",
        156 => "tempo",
        159 => "build number",
        160 => "pattern channel",
        161 => "pattern channel loop",
        162 => "pattern loop",
        164 => "pattern length",
        192 => "channel name (legacy)",
        193 => "pattern name",
        194 => "title",
        195 => "comments",
        196 => "sample path",
        197 => "web link",
        198 => "comments (rich text)",
        199 => "version",
        200 => "licensee",
        201 => "plugin internal name",
        202 => "data path",
        203 => "plugin name",
        204 => "insert name",
        205 => "marker name",
        206 => "genre",
        207 => "author",
        208 => "MIDI controls (legacy)",
        209 => "channel delay",
        210 => "TS404 parameters (legacy)",
        211 => "delay line (legacy)",
        212 => "plugin wrapper",
        213 => "plugin state",
        215 => "channel parameters",
        216 => "initial control values",
        217 => "playlist selection",
        218 => "envelope and LFO",
        219 => "channel levels",
        220 => "filter (legacy)",
        221 => "polyphony",
        223 => "pattern control events",
        224 => "pattern notes",
        225 => "mixer control values",
        226 => "MIDI controller",
        227 => "remote controller",
        228 => "tracking",
        229 => "level adjustments",
        230 => "remote controller formula",
        231 => "channel group name",
        233 => "playlist items",
        234 => "automation clip data",
        235 => "insert routing",
        236 => "insert flags",
        237 => "timestamp",
        238 => "playlist track",
        239 => "playlist track name",
        241 => "arrangement name",
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::event_name;

    #[test]
    fn known_ids_have_names_and_new_ones_do_not() {
        assert_eq!(event_name(224), Some("pattern notes"));
        assert_eq!(event_name(199), Some("version"));
        assert_eq!(event_name(250), None);
        assert_eq!(event_name(63), None);
    }
}
