[package]
name = "windfall-dsp"
description = "Windfall's built-in effects and instruments, and the signal processing blocks they are made of"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
windfall-core.workspace = true
serde.workspace = true
ts-rs.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
