#!/usr/bin/env bash
# Regenerates the TypeScript bindings for the project model and IPC types.
# Run from anywhere: scripts/gen-bindings.sh
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/apps/desktop/src/bindings"

cd "$root"
mkdir -p "$out"
rm -f "$out"/*.ts
cargo test --workspace --quiet export_bindings >/dev/null

{
  echo "// Generated by scripts/gen-bindings.sh. Do not edit."
  for file in "$out"/*.ts; do
    name="$(basename "$file" .ts)"
    [ "$name" = "index" ] && continue
    echo "export type { $name } from \"./$name\";"
  done
} >"$out/index.ts"
echo "wrote $(ls "$out" | wc -l) files to apps/desktop/src/bindings"
