#!/usr/bin/env bash
# Regenerates the TypeScript bindings for the project model and IPC types,
# and the parameter tables of the built-in effects and instruments.
# Run from anywhere: scripts/gen-bindings.sh [output-directory]
# CI supplies an empty temporary directory, leaving checked-in files alone.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ "$#" -gt 1 ]; then
  echo "usage: scripts/gen-bindings.sh [output-directory]" >&2
  exit 1
fi
out="${1:-$root/apps/desktop/src/bindings}"
mkdir -p "$out"
out="$(cd "$out" && pwd)"

# Rust consumes native paths, rather than Git Bash's /c/... paths.
if command -v cygpath >/dev/null; then
  export TS_RS_EXPORT_DIR="$(cygpath -w "$out")"
else
  export TS_RS_EXPORT_DIR="$out"
fi
case "$(uname -s)" in
  MINGW* | MSYS* | CYGWIN*) source "$root/scripts/msvc-env.sh" ;;
esac
# Keep the barrel's order identical on each runner.
export LC_ALL=C

cd "$root"
rm -f "$out"/*.ts
# These libraries own every #[ts(export)] type. Their exports also write
# referenced types from dependencies; compiling the Tauri shell adds none.
cargo test -p windfall-dsp -p windfall-project -p windfall-ipc --lib --quiet export_bindings >/dev/null
if ! compgen -G "$out/*.ts" >/dev/null; then
  echo "gen-bindings: no TypeScript types were exported to $out" >&2
  exit 1
fi

{
  echo "// Generated by scripts/gen-bindings.sh. Do not edit."
  for file in "$out"/*.ts; do
    name="$(basename "$file" .ts)"
    [ "$name" = "index" ] && continue
    echo "export type { $name } from \"./$name\";"
  done
} >"$out/index.ts"
# Parameter tables and default settings of every effect and instrument, plus
# reference curves the UI's display code is tested against.
cargo run --quiet -p windfall-dsp --example descriptors >"$out/descriptors.json"
cargo run --quiet -p windfall-project --example automation_fixtures >"$out/automation-fixtures.json"

echo "wrote $(ls "$out" | wc -l) files to $out"
