//! The control names and JSON paths of the indexed banks.
//!
//! A [`ParamInfo`](crate::ParamInfo) carries its path and its name as
//! `&'static str`, and a constant cannot build a string, so the banks that
//! have one row per partial spell theirs out. Nothing here is edited by
//! hand: each table is one entry per index, in index order.

/// `gains.0` to `gains.63` of [`HarmonicStackParams`](super::HarmonicStackParams).
pub(super) static STACK_GAIN_IDS: [&str; 64] = [
    "gains.0", "gains.1", "gains.2", "gains.3", "gains.4", "gains.5", "gains.6", "gains.7",
    "gains.8", "gains.9", "gains.10", "gains.11", "gains.12", "gains.13", "gains.14", "gains.15",
    "gains.16", "gains.17", "gains.18", "gains.19", "gains.20", "gains.21", "gains.22", "gains.23",
    "gains.24", "gains.25", "gains.26", "gains.27", "gains.28", "gains.29", "gains.30", "gains.31",
    "gains.32", "gains.33", "gains.34", "gains.35", "gains.36", "gains.37", "gains.38", "gains.39",
    "gains.40", "gains.41", "gains.42", "gains.43", "gains.44", "gains.45", "gains.46", "gains.47",
    "gains.48", "gains.49", "gains.50", "gains.51", "gains.52", "gains.53", "gains.54", "gains.55",
    "gains.56", "gains.57", "gains.58", "gains.59", "gains.60", "gains.61", "gains.62", "gains.63",
];

/// `Partial 1` to `Partial 64`.
pub(super) static PARTIAL_NAMES: [&str; 64] = [
    "Partial 1",
    "Partial 2",
    "Partial 3",
    "Partial 4",
    "Partial 5",
    "Partial 6",
    "Partial 7",
    "Partial 8",
    "Partial 9",
    "Partial 10",
    "Partial 11",
    "Partial 12",
    "Partial 13",
    "Partial 14",
    "Partial 15",
    "Partial 16",
    "Partial 17",
    "Partial 18",
    "Partial 19",
    "Partial 20",
    "Partial 21",
    "Partial 22",
    "Partial 23",
    "Partial 24",
    "Partial 25",
    "Partial 26",
    "Partial 27",
    "Partial 28",
    "Partial 29",
    "Partial 30",
    "Partial 31",
    "Partial 32",
    "Partial 33",
    "Partial 34",
    "Partial 35",
    "Partial 36",
    "Partial 37",
    "Partial 38",
    "Partial 39",
    "Partial 40",
    "Partial 41",
    "Partial 42",
    "Partial 43",
    "Partial 44",
    "Partial 45",
    "Partial 46",
    "Partial 47",
    "Partial 48",
    "Partial 49",
    "Partial 50",
    "Partial 51",
    "Partial 52",
    "Partial 53",
    "Partial 54",
    "Partial 55",
    "Partial 56",
    "Partial 57",
    "Partial 58",
    "Partial 59",
    "Partial 60",
    "Partial 61",
    "Partial 62",
    "Partial 63",
    "Partial 64",
];

/// `snapshotA.0` to `snapshotA.31` of [`PartialMorphParams`](super::PartialMorphParams).
pub(super) static MORPH_A_IDS: [&str; 32] = [
    "snapshotA.0",
    "snapshotA.1",
    "snapshotA.2",
    "snapshotA.3",
    "snapshotA.4",
    "snapshotA.5",
    "snapshotA.6",
    "snapshotA.7",
    "snapshotA.8",
    "snapshotA.9",
    "snapshotA.10",
    "snapshotA.11",
    "snapshotA.12",
    "snapshotA.13",
    "snapshotA.14",
    "snapshotA.15",
    "snapshotA.16",
    "snapshotA.17",
    "snapshotA.18",
    "snapshotA.19",
    "snapshotA.20",
    "snapshotA.21",
    "snapshotA.22",
    "snapshotA.23",
    "snapshotA.24",
    "snapshotA.25",
    "snapshotA.26",
    "snapshotA.27",
    "snapshotA.28",
    "snapshotA.29",
    "snapshotA.30",
    "snapshotA.31",
];

/// `A partial 1` to `A partial 32`.
pub(super) static MORPH_A_NAMES: [&str; 32] = [
    "A partial 1",
    "A partial 2",
    "A partial 3",
    "A partial 4",
    "A partial 5",
    "A partial 6",
    "A partial 7",
    "A partial 8",
    "A partial 9",
    "A partial 10",
    "A partial 11",
    "A partial 12",
    "A partial 13",
    "A partial 14",
    "A partial 15",
    "A partial 16",
    "A partial 17",
    "A partial 18",
    "A partial 19",
    "A partial 20",
    "A partial 21",
    "A partial 22",
    "A partial 23",
    "A partial 24",
    "A partial 25",
    "A partial 26",
    "A partial 27",
    "A partial 28",
    "A partial 29",
    "A partial 30",
    "A partial 31",
    "A partial 32",
];

/// `snapshotB.0` to `snapshotB.31`.
pub(super) static MORPH_B_IDS: [&str; 32] = [
    "snapshotB.0",
    "snapshotB.1",
    "snapshotB.2",
    "snapshotB.3",
    "snapshotB.4",
    "snapshotB.5",
    "snapshotB.6",
    "snapshotB.7",
    "snapshotB.8",
    "snapshotB.9",
    "snapshotB.10",
    "snapshotB.11",
    "snapshotB.12",
    "snapshotB.13",
    "snapshotB.14",
    "snapshotB.15",
    "snapshotB.16",
    "snapshotB.17",
    "snapshotB.18",
    "snapshotB.19",
    "snapshotB.20",
    "snapshotB.21",
    "snapshotB.22",
    "snapshotB.23",
    "snapshotB.24",
    "snapshotB.25",
    "snapshotB.26",
    "snapshotB.27",
    "snapshotB.28",
    "snapshotB.29",
    "snapshotB.30",
    "snapshotB.31",
];

/// `B partial 1` to `B partial 32`.
pub(super) static MORPH_B_NAMES: [&str; 32] = [
    "B partial 1",
    "B partial 2",
    "B partial 3",
    "B partial 4",
    "B partial 5",
    "B partial 6",
    "B partial 7",
    "B partial 8",
    "B partial 9",
    "B partial 10",
    "B partial 11",
    "B partial 12",
    "B partial 13",
    "B partial 14",
    "B partial 15",
    "B partial 16",
    "B partial 17",
    "B partial 18",
    "B partial 19",
    "B partial 20",
    "B partial 21",
    "B partial 22",
    "B partial 23",
    "B partial 24",
    "B partial 25",
    "B partial 26",
    "B partial 27",
    "B partial 28",
    "B partial 29",
    "B partial 30",
    "B partial 31",
    "B partial 32",
];

/// The ratio, level and phase of each row of
/// [`ResynthParams::table`](super::ResynthParams::table), three per partial.
pub(super) static RESYNTH_IDS: [&str; 96] = [
    "table.0.ratio",
    "table.0.gain",
    "table.0.phase",
    "table.1.ratio",
    "table.1.gain",
    "table.1.phase",
    "table.2.ratio",
    "table.2.gain",
    "table.2.phase",
    "table.3.ratio",
    "table.3.gain",
    "table.3.phase",
    "table.4.ratio",
    "table.4.gain",
    "table.4.phase",
    "table.5.ratio",
    "table.5.gain",
    "table.5.phase",
    "table.6.ratio",
    "table.6.gain",
    "table.6.phase",
    "table.7.ratio",
    "table.7.gain",
    "table.7.phase",
    "table.8.ratio",
    "table.8.gain",
    "table.8.phase",
    "table.9.ratio",
    "table.9.gain",
    "table.9.phase",
    "table.10.ratio",
    "table.10.gain",
    "table.10.phase",
    "table.11.ratio",
    "table.11.gain",
    "table.11.phase",
    "table.12.ratio",
    "table.12.gain",
    "table.12.phase",
    "table.13.ratio",
    "table.13.gain",
    "table.13.phase",
    "table.14.ratio",
    "table.14.gain",
    "table.14.phase",
    "table.15.ratio",
    "table.15.gain",
    "table.15.phase",
    "table.16.ratio",
    "table.16.gain",
    "table.16.phase",
    "table.17.ratio",
    "table.17.gain",
    "table.17.phase",
    "table.18.ratio",
    "table.18.gain",
    "table.18.phase",
    "table.19.ratio",
    "table.19.gain",
    "table.19.phase",
    "table.20.ratio",
    "table.20.gain",
    "table.20.phase",
    "table.21.ratio",
    "table.21.gain",
    "table.21.phase",
    "table.22.ratio",
    "table.22.gain",
    "table.22.phase",
    "table.23.ratio",
    "table.23.gain",
    "table.23.phase",
    "table.24.ratio",
    "table.24.gain",
    "table.24.phase",
    "table.25.ratio",
    "table.25.gain",
    "table.25.phase",
    "table.26.ratio",
    "table.26.gain",
    "table.26.phase",
    "table.27.ratio",
    "table.27.gain",
    "table.27.phase",
    "table.28.ratio",
    "table.28.gain",
    "table.28.phase",
    "table.29.ratio",
    "table.29.gain",
    "table.29.phase",
    "table.30.ratio",
    "table.30.gain",
    "table.30.phase",
    "table.31.ratio",
    "table.31.gain",
    "table.31.phase",
];

/// The names of [`RESYNTH_IDS`], in the same order.
pub(super) static RESYNTH_NAMES: [&str; 96] = [
    "Partial 1 ratio",
    "Partial 1 level",
    "Partial 1 phase",
    "Partial 2 ratio",
    "Partial 2 level",
    "Partial 2 phase",
    "Partial 3 ratio",
    "Partial 3 level",
    "Partial 3 phase",
    "Partial 4 ratio",
    "Partial 4 level",
    "Partial 4 phase",
    "Partial 5 ratio",
    "Partial 5 level",
    "Partial 5 phase",
    "Partial 6 ratio",
    "Partial 6 level",
    "Partial 6 phase",
    "Partial 7 ratio",
    "Partial 7 level",
    "Partial 7 phase",
    "Partial 8 ratio",
    "Partial 8 level",
    "Partial 8 phase",
    "Partial 9 ratio",
    "Partial 9 level",
    "Partial 9 phase",
    "Partial 10 ratio",
    "Partial 10 level",
    "Partial 10 phase",
    "Partial 11 ratio",
    "Partial 11 level",
    "Partial 11 phase",
    "Partial 12 ratio",
    "Partial 12 level",
    "Partial 12 phase",
    "Partial 13 ratio",
    "Partial 13 level",
    "Partial 13 phase",
    "Partial 14 ratio",
    "Partial 14 level",
    "Partial 14 phase",
    "Partial 15 ratio",
    "Partial 15 level",
    "Partial 15 phase",
    "Partial 16 ratio",
    "Partial 16 level",
    "Partial 16 phase",
    "Partial 17 ratio",
    "Partial 17 level",
    "Partial 17 phase",
    "Partial 18 ratio",
    "Partial 18 level",
    "Partial 18 phase",
    "Partial 19 ratio",
    "Partial 19 level",
    "Partial 19 phase",
    "Partial 20 ratio",
    "Partial 20 level",
    "Partial 20 phase",
    "Partial 21 ratio",
    "Partial 21 level",
    "Partial 21 phase",
    "Partial 22 ratio",
    "Partial 22 level",
    "Partial 22 phase",
    "Partial 23 ratio",
    "Partial 23 level",
    "Partial 23 phase",
    "Partial 24 ratio",
    "Partial 24 level",
    "Partial 24 phase",
    "Partial 25 ratio",
    "Partial 25 level",
    "Partial 25 phase",
    "Partial 26 ratio",
    "Partial 26 level",
    "Partial 26 phase",
    "Partial 27 ratio",
    "Partial 27 level",
    "Partial 27 phase",
    "Partial 28 ratio",
    "Partial 28 level",
    "Partial 28 phase",
    "Partial 29 ratio",
    "Partial 29 level",
    "Partial 29 phase",
    "Partial 30 ratio",
    "Partial 30 level",
    "Partial 30 phase",
    "Partial 31 ratio",
    "Partial 31 level",
    "Partial 31 phase",
    "Partial 32 ratio",
    "Partial 32 level",
    "Partial 32 phase",
];

/// `row.0` to `row.31` of [`ScanSynthParams`](super::ScanSynthParams).
pub(super) static SCAN_ROW_IDS: [&str; 32] = [
    "row.0", "row.1", "row.2", "row.3", "row.4", "row.5", "row.6", "row.7", "row.8", "row.9",
    "row.10", "row.11", "row.12", "row.13", "row.14", "row.15", "row.16", "row.17", "row.18",
    "row.19", "row.20", "row.21", "row.22", "row.23", "row.24", "row.25", "row.26", "row.27",
    "row.28", "row.29", "row.30", "row.31",
];

/// `Step 1` to `Step 32`.
pub(super) static SCAN_ROW_NAMES: [&str; 32] = [
    "Step 1", "Step 2", "Step 3", "Step 4", "Step 5", "Step 6", "Step 7", "Step 8", "Step 9",
    "Step 10", "Step 11", "Step 12", "Step 13", "Step 14", "Step 15", "Step 16", "Step 17",
    "Step 18", "Step 19", "Step 20", "Step 21", "Step 22", "Step 23", "Step 24", "Step 25",
    "Step 26", "Step 27", "Step 28", "Step 29", "Step 30", "Step 31", "Step 32",
];
